import{collection,doc,getDocFromServer,getDocsFromServer,query,where,limit,runTransaction}from'firebase/firestore';import{db}from'../firebase/config';import{owner}from'../business/service';import{ImportRow,basicValidation,specs}from'./model';
export type ImportDraft={id:string;ownerUid:string;target:string;rows:ImportRow[];createdAt:string;state:'reviewed_reference';version:1};
export function validateDraft(target:string,rows:ImportRow[]){const s=specs[target];if(!s||!rows.length||rows.length>200)throw Error('Choose a supported list and 1-200 rows.');const seen=new Set<string>();for(const row of rows){if(Object.keys(row).some(k=>!s.fields.includes(k))||s.fields.some(k=>typeof row[k]!=='string'))throw Error('Unexpected import fields.');const e=basicValidation(row,s);if(e.length)throw Error(e.join('; '));const text=JSON.stringify(row);if(seen.has(text))throw Error('Duplicate row.');seen.add(text);}if(JSON.stringify(rows).length>500000)throw Error('Draft exceeds500KB. Split the batch.');}
const equalRows=(a:ImportRow[],b:ImportRow[])=>a.length===b.length&&a.every((r,i)=>Object.keys(r).length===Object.keys(b[i]).length&&Object.keys(r).every(k=>r[k]===b[i][k]));
export async function draftId(uid:string,target:string,rows:ImportRow[]){const canonical=JSON.stringify({uid,target,rows:rows.map(r=>Object.fromEntries(Object.keys(r).sort().map(k=>[k,r[k]])))});const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));return 'IMPORT-'+Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function saveDraft(target:string,rows:ImportRow[]){validateDraft(target,rows);const uid=owner().uid,id=await draftId(uid,target,rows),ref=doc(db,'managementImportDrafts',id),now=new Date().toISOString();await runTransaction(db,async tx=>{if(owner().uid!==uid)throw Error('Account changed.');const d=await tx.get(ref);if(d.exists()){if(d.data().ownerUid!==uid||d.data().target!==target||!equalRows(d.data().rows,rows))throw Error('Draft reference conflict. No overwrite.');return;}tx.set(ref,{id,ownerUid:uid,target,rows,createdAt:now,state:'reviewed_reference',version:1});});const check=await getDocFromServer(ref);if(owner().uid!==uid||!check.exists()||check.data().target!==target||!equalRows(check.data().rows,rows))throw Error('Draft save not confirmed. Retry same rows; do not create a new batch.');return check.data()as ImportDraft;}
export async function readDrafts(target:string){const uid=owner().uid,s=await getDocsFromServer(query(collection(db,'managementImportDrafts'),where('ownerUid','==',uid),where('target','==',target),limit(51)));if(owner().uid!==uid)throw Error('Account changed.');if(s.size>50)throw Error('More than50draft batches. Paging required; no full list assumed.');return s.docs.map(d=>d.data()as ImportDraft).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));}
export type ApprovedImport={id:string;ownerUid:string;draftId:string;target:string;row:ImportRow;rowNumber:number;approvedAt:string;state:'approved_reference';version:1};
export async function approveReferences(opened:ImportDraft,progress:(n:number)=>void){const uid=owner().uid;if(opened.ownerUid!==uid)throw Error('Draft owner changed.');const fresh=await getDocFromServer(doc(db,'managementImportDrafts',opened.id));if(!fresh.exists()||fresh.data().target!==opened.target||!equalRows(fresh.data().rows,opened.rows))throw Error('Draft changed. Refresh and review again.');validateDraft(opened.target,opened.rows);const now=new Date().toISOString();for(let i=0;i<opened.rows.length;i++){const id=opened.id+'-'+i,ref=doc(db,'managementImportedReferences',id);await runTransaction(db,async tx=>{if(owner().uid!==uid)throw Error('Account changed. Approval stopped.');const d=await tx.get(ref);if(d.exists()){if(d.data().ownerUid!==uid||d.data().draftId!==opened.id||!equalRows([d.data().row],[opened.rows[i]]))throw Error('Reference conflict. No overwrite.');return;}tx.set(ref,{id,ownerUid:uid,draftId:opened.id,target:opened.target,row:opened.rows[i],rowNumber:i,approvedAt:now,state:'approved_reference',version:1});});const check=await getDocFromServer(ref);if(owner().uid!==uid||!check.exists()||!equalRows([check.data().row],[opened.rows[i]]))throw Error('Approval readback failed. Retry this same batch, not a new upload.');progress(i+1);}return opened.rows.length;}
export async function readApproved(target:string){const uid=owner().uid,s=await getDocsFromServer(query(collection(db,'managementImportedReferences'),where('ownerUid','==',uid),where('target','==',target),limit(201)));if(owner().uid!==uid)throw Error('Account changed.');return {rows:s.docs.map(d=>d.data()as ApprovedImport).sort((a,b)=>b.approvedAt.localeCompare(a.approvedAt)),capped:s.size===201};}
