export type ImportRow=Record<string,string>;
export type ImportSpec={id:string;label:string;fields:string[];required:string[];sample:string[];notice:string};
const draft='Reviewed reference draft only. No original record, payment, stock, account, tax filing or notification is changed.';
const spec=(id:string,label:string,fields:string[],required:string[],sample:string[],notice=draft):ImportSpec=>({id,label,fields,required,sample,notice});
export const specs:Record<string,ImportSpec>={
 contacts:spec('contacts','Manual contact list',['name','company','phone','email','city','address','sourceReference','note'],['name','phone'],['Example buyer','Example business','919000000000','buyer@example.invalid','Kolkata','Example address','IMPORT-EXAMPLE','Example only'],'Adds unverified manual contacts only. Does not create login accounts, link orders or send messages.'),
 employees:spec('employees','Cloud employees',['name','email','phone','designation','department','baseSalary','joiningDate','role'],['name','designation','department','baseSalary','joiningDate','role'],['Example employee','employee@example.invalid','919000000000','Assistant','Operations','15000.00','2026-01-01','inventory'],'Adds cloud employee directory records only. No login access or salary payment.'),
 attendance:spec('attendance','Attendance',['employeeId','date','status','note'],['employeeId','date','status'],['EMP-example-id','2026-01-01','present','Verified from register']),
 salary:spec('salary','Salary references',['employeeId','month','basic','allowances','deductions','payDate','reference'],['employeeId','month','basic','allowances','deductions'],['EMP-example-id','2026-01','15000.00','0.00','0.00','2026-02-01','PAY-EXAMPLE']),
 products:spec('products','Product listing',['sku','name','category','price','stock','hsn','gstRate','description'],['sku','name','category','price','stock','hsn','gstRate'],['EXAMPLE-001','Example product','kitchen','500.00','10','732393','18','Example only']),
 stock:spec('stock','Stock references',['productId','sku','quantity','date','reference','reason'],['productId','quantity','date','reference'],['prod-example','EXAMPLE-001','10','2026-01-01','COUNT-EXAMPLE','Physical count']),
 orders:spec('orders','Order references',['orderId','customerName','phone','email','date','total','address','source'],['orderId','customerName','date','total','source'],['EXTERNAL-EXAMPLE','Example buyer','919000000000','buyer@example.invalid','2026-01-01','500.00','Example address','External register']),
 customers:spec('customers','Customer references',['name','company','phone','email','address','sourceReference'],['name','phone'],['Example buyer','Example business','919000000000','buyer@example.invalid','Example address','EXAMPLE']),
 investors:spec('investors','Investor references',['name','company','phone','email','amount','note','sourceReference'],['name','phone'],['Example investor','Example business','919000000000','buyer@example.invalid','50000.00','Unverified expression of interest','EXAMPLE']),
 rfq:spec('rfq','Wholesale inquiry references',['businessName','contactPerson','phone','email','message','sourceReference'],['businessName','contactPerson','phone'],['Example business','Example buyer','919000000000','buyer@example.invalid','Quotation requested','EXAMPLE']),
 expenses:spec('expenses','Expense references',['date','amount','category','reference','note'],['date','amount','category','reference'],['2026-01-01','500.00','shipping','EXP-EXAMPLE','Verified receipt']),
 bank:spec('bank','Bank statement review',['Date','Description','Debit','Credit','Reference'],['Date','Description'],['2026-01-01','Example transaction','500.00','','BANK-EXAMPLE'],'Statement review only. Use the existing bank statement Confirm import for private unclassified ledger entries. No balance or payout assumed.'),
 quotation:spec('quotation','Quotation customers',['business','contact','phone','email','gstin','billing','shipping','state','postcode','country'],['business'],['Example business','Example buyer','919000000000','buyer@example.invalid','','Example address','Example address','West Bengal','721152','India'],'Customer reference review only. Existing quotation editor must review price, quantity, tax and terms before publication.'),
 gst:spec('gst','GST source references',['invoiceNumber','date','gstin','placeOfSupply','taxableValue','cgst','sgst','igst','sourceReference'],['invoiceNumber','date','placeOfSupply','taxableValue','cgst','sgst','igst','sourceReference'],['EXAMPLE-001','2026-01-01','','19','500.00','45.00','45.00','0.00','Supplier invoice']),
 tasks:spec('tasks','Task references',['title','assignedTo','dueDate','note'],['title'],['Example task','Employee reference','2026-01-01','No automatic assignment or reminder']),
 history:spec('history','Historical references',['date','reference','description','source'],['date','reference','description','source'],['2026-01-01','EXAMPLE','External reference only','Owner register'],'External reference only. Never creates audit events, delivery receipts, sent messages or verified history.')
};
export function parseCsv(text:string):string[][]{
 if(text.length>1000000)throw Error('Use a file under 1 MB.');text=text.replace(/^\uFEFF/,'');
 const rows:string[][]=[],row:string[]=[];let cell='',quoted=false,closed=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;}else if(c==='"'){if(cell||closed)throw Error('Unexpected quote. Check CSV format.');quoted=true;}else if(c===','||c==='\n'||c==='\r'){row.push(cell);cell='';closed=false;if(c!==','){if(c==='\r'&&text[i+1]==='\n')i++;if(row.some(v=>v.trim()))rows.push([...row]);row.length=0;}}else{if(closed&&c!==' '&&c!=='\t')throw Error('Unexpected text after closing quote.');if(!closed)cell+=c;}if(cell.length>4000||row.length>50||rows.length>201)throw Error('Limit: 200 rows, 50 columns and 4000 characters per cell.');}
 if(quoted)throw Error('Unclosed CSV quote.');row.push(cell);if(row.some(v=>v.trim()))rows.push([...row]);if(rows.length<2)throw Error('Include a header and at least one data row.');if(rows.length>201||rows[0].length>50)throw Error('Limit: 200 rows and 50 columns.');const width=rows[0].length;if(rows.some(r=>r.length!==width))throw Error('Rows have different column counts. Check delimiters and quotes.');const head=rows[0].map(x=>x.trim());if(head.some(x=>!x)||new Set(head.map(x=>x.toLowerCase())).size!==head.length)throw Error('Headers must be non-empty and unique.');return [head,...rows.slice(1)];
}
export function rawCsv(rows:string[][]){return rows.map(r=>r.map(v=>'"'+v.replace(/"/g,'""')+'"').join(',')).join('\r\n');}
export function mapRows(rows:string[][],mapping:Record<string,string>,fields:string[]):ImportRow[]{return rows.slice(1).map(r=>Object.fromEntries(fields.map(k=>[k,mapping[k]===''?'':(r[Number(mapping[k])]||'').trim()])));}
export function basicValidation(row:ImportRow,s:ImportSpec):string[]{const errors=s.required.filter(k=>!row[k]?.trim()).map(k=>k+' is required');for(const [k,v]of Object.entries(row)){if(v.length>4000)errors.push(k+' is too long');if(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(v))errors.push(k+' contains control characters');if(/^\s*[=@]/.test(v))errors.push(k+' contains a spreadsheet formula');if(k.toLowerCase().includes('email')&&v&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))errors.push('Check email');if(['date','joiningDate','payDate','dueDate','Date'].includes(k)&&v){const d=new Date(v+'T12:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==v)errors.push(k+' must be a real YYYY-MM-DD date');}if(['price','baseSalary','total','amount','basic','allowances','deductions','taxableValue','cgst','sgst','igst','Debit','Credit'].includes(k)&&v&&!/^\d+(\.\d{1,2})?$/.test(v))errors.push(k+' must be non-negative, at most 2 decimals');if(['stock','quantity'].includes(k)&&v&&!/^\d+$/.test(v))errors.push(k+' must be a non-negative whole number');}return errors;}
