export type PayPolicy={basis:''|'daily'|'monthly';amount:string;divisor:string;half:string;leave:string;absent:string;present:string;confirmed:boolean};
export type PayDay={date:string;status:'present'|'half-day'|'absent'|'leave'};
export function monthDates(month:string){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(month))throw Error('Choose a valid month.');const[y,m]=month.split('-').map(Number);return Array.from({length:new Date(Date.UTC(y,m,0)).getUTCDate()},(_,i)=>month+'-'+String(i+1).padStart(2,'0'));}
function num(s:string,label:string,max:number){if(!/^\d+(\.\d{1,2})?$/.test(s)||Number(s)>max)throw Error('Enter verified '+label+'.');return Number(s);}
export function calculatePay(month:string,joiningDate:string,rows:PayDay[],p:PayPolicy,cutoff:string){if(!p.confirmed||!p.basis)throw Error('Review and confirm the pay policy first.');const amount=num(p.amount,'pay amount',10000000);if(amount<=0)throw Error('Pay amount must be positive.');const divisor=p.basis==='daily'?1:num(p.divisor,'monthly divisor',366);if(divisor<=0)throw Error('Monthly divisor must be positive.');const factors={present:num(p.present,'present factor',1),'half-day':num(p.half,'half-day factor',1),absent:num(p.absent,'absent factor',1),leave:num(p.leave,'leave factor',1)};const days=monthDates(month).filter(d=>d>=joiningDate);const dates=new Set<string>();const map=new Map<string,PayDay>();for(const row of rows){if(!days.includes(row.date))continue;if(dates.has(row.date))throw Error('Duplicate attendance date. Review source records.');dates.add(row.date);map.set(row.date,row);}let units=0,present=0,missing=0;const detail=days.map(date=>{const r=map.get(date);if(!r){missing++;return{date,status:'unmarked',units:null,pay:null}}if(date>cutoff)throw Error('Future attendance needs review before payroll.');if(!(r.status in factors))throw Error('Unknown attendance status.');const f=factors[r.status];units+=f;if(r.status==='present')present++;return{date,status:r.status,units:f,pay:Math.round(amount/divisor*f*100)/100}});return{rate:amount/divisor,units,present,missing,total:Math.round(amount/divisor*units*100)/100,detail};}
export function money(value:number){return value.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})}
const small=['Zero','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'];const tens=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];function words(n:number):string{if(n<20)return small[n];if(n<100)return tens[Math.floor(n/10)]+(n%10?' '+small[n%10]:'');if(n<1000)return words(Math.floor(n/100))+' Hundred'+(n%100?' '+words(n%100):'');for(const[base,label]of[[10000000,'Crore'],[100000,'Lakh'],[1000,'Thousand']]as const)if(n>=base)return words(Math.floor(n/base))+' '+label+(n%base?' '+words(n%base):'');return'';}
export function amountWords(n:number){if(!Number.isFinite(n)||n<0||n>100000000)throw Error('Invalid net salary.');const paise=Math.round(n*100),rupees=Math.floor(paise/100);return'Rupees '+words(rupees)+(paise%100?' and '+words(paise%100)+' Paise':'')+' Only';}
export function salaryTotals(earnings:string[],deductions:string[]){const e=earnings.map(x=>num(x,'earning amount (enter 0 if none)',10000000)),d=deductions.map(x=>num(x,'deduction amount (enter 0 if none)',10000000));const gross=Math.round(e.reduce((a,b)=>a+b,0)*100)/100,less=Math.round(d.reduce((a,b)=>a+b,0)*100)/100;const net=Math.round((gross-less)*100)/100;if(net<0)throw Error('Deductions exceed earnings. Review before export.');return{gross,less,net,words:amountWords(net)};}
