import{money,salaryTotals}from'./payrollDraft';import{salaryTemplateBackground}from'./salaryTemplateBackground';
export type SalaryInput={employeeName:string;employeeId:string;designation:string;department:string;joiningDate:string;bank:string;period:string;payDate:string;pan:string;uan:string;earnings:string[];deductions:string[]};
// Original supplied DOCX render is the background. Only owner-entered fields and confirmed phone are replaced.
export async function salaryCanvas(d:SalaryInput){const totals=salaryTotals(d.earnings,d.deductions),canvas=document.createElement('canvas');canvas.width=1240;canvas.height=1754;const c=canvas.getContext('2d');if(!c)throw Error('PDF preview unavailable.');const base=new Image();base.src=salaryTemplateBackground;await base.decode();c.drawImage(base,0,0,1240,1754);const sx=1240/902,sy=1754/1274;c.scale(sx,sy);const navy='#1d3d65',gray='#525a63';function text(t:string,x:number,y:number,size:number,bold=false,color=gray){c.fillStyle=color;c.font=(bold?'bold ':'')+size+'px Arial';c.fillText(t,x,y)}function fitted(t:string,x:number,y:number,width:number,size=12){let s=size;while(s>8){c.font=s+'px Arial';if(c.measureText(t).width<=width)break;s-=.25}if(c.measureText(t).width>width)throw Error('Employee field too long for supplied salary layout. Shorten the verified display value before export.');text(t,x,y,s)}function field(t:string,x:number,y:number,width:number){c.fillStyle='white';c.fillRect(x,y-17,width,28);fitted(t||'Not supplied',x+3,y,width-8)}
// Keep original two-column details, header, row heights, watermark and signatures.
c.fillStyle='white';c.fillRect(282,173,341,25);text('For the Month of '+new Date(d.period+'-01T12:00:00+05:30').toLocaleDateString('en-IN',{month:'long',year:'numeric'}),286,190,14);
const left=[d.employeeName,d.designation,d.joiningDate,d.period,d.pan],right=[d.employeeId,d.department,d.bank,d.payDate,d.uan],lx=[203,176,196,166,148],rx=[552,547,551,518,555];for(let i=0;i<5;i++){const y=258+i*32.5;field(left[i],lx[i],y,447-lx[i]);field(right[i],rx[i],y,824-rx[i]);}
const rowYs=[498,540,573,605,637,669,704];for(let i=0;i<7;i++){const y=rowYs[i];const e=i===6?money(totals.gross):money(Number(d.earnings[i])),de=i===6?money(totals.less):i<5?money(Number(d.deductions[i])):'';text(e,277,y,13,i===6,navy);text(de,650,y,13,i===6,navy)}
c.fillStyle=navy;c.fillRect(79,771,745,54);text('NET SALARY PAYABLE:  ₹ '+money(totals.net),89,795,16,true,'white');let size=12;c.font=size+'px Arial';while(c.measureText(totals.words).width>722&&size>9){size-=.25;c.font=size+'px Arial'}if(c.measureText(totals.words).width>722)throw Error('Salary words too long for supplied layout.');text(totals.words,89,814,size,false,'white');
c.fillStyle='white';c.fillRect(240,1206,423,17);text('Phone: +91-9845485437  |  Email: ecommerceunickdigital@gmail.com',243,1218,9,false,'#808080');return canvas;}
