import{type Firestore,runTransaction,doc,setDoc,getDocFromServer,deleteDoc,serverTimestamp,updateDoc,collection,query,orderBy,limit,getDocsFromServer}from'firebase/firestore';
import{customerAuth,customerDb}from'./customerIdentity';
import{validateB2b}from'./b2bValidation';
export type B2bRecord={businessName:string;gstin:string;pan:string;deliveryAddress:string;email:string;status:'pending'|'approved'|'needs_changes';noticeVersion:'b2b-identity-v1';updatedAt:unknown;reviewedAt?:unknown};
function identity(uid?:string){const u=customerAuth.currentUser;if(!u?.emailVerified||!u.email||(uid&&uid!==u.uid))throw Error('Sign in with your verified email.');return u;}
export async function ownB2b(){const u=identity();const d=await getDocFromServer(doc(customerDb,'b2bRegistrations',u.uid));identity(u.uid);return d.exists()?d.data()as B2bRecord:null;}
export async function saveB2b(businessName:string,gstin:string,pan:string,deliveryAddress:string){const u=identity();const value={...validateB2b(businessName,gstin,pan,deliveryAddress),email:u.email!,status:'pending',noticeVersion:'b2b-identity-v1',updatedAt:serverTimestamp()};const r=doc(customerDb,'b2bRegistrations',u.uid);await setDoc(r,value);identity(u.uid);const d=await getDocFromServer(r);identity(u.uid);if(!d.exists()||Object.entries(value).filter(([k])=>k!=='updatedAt').some(([k,v])=>d.data()[k]!==v))throw Error('Save could not be confirmed. Check your registration before trying again.');return d.data()as B2bRecord;}
export async function closeB2b(){const u=identity();const r=doc(customerDb,'b2bRegistrations',u.uid);await deleteDoc(r);identity(u.uid);if((await getDocFromServer(r)).exists())throw Error('Deletion could not be confirmed.');identity(u.uid);}
// Owner review uses the existing owner Firebase app, never customer auth or a public export.
export async function listB2b(db:Firestore){const rows=await getDocsFromServer(query(collection(db,'b2bRegistrations'),orderBy('updatedAt','desc'),limit(50)));return rows.docs.map(d=>({id:d.id,...d.data()}as B2bRecord&{id:string}));}
export async function reviewB2b(db:Firestore,id:string,status:'approved'|'needs_changes',expected:B2bRecord){const r=doc(db,'b2bRegistrations',id);await runTransaction(db,async tx=>{const d=await tx.get(r);if(!d.exists()||['businessName','gstin','pan','deliveryAddress','email','status'].some(k=>d.data()[k]!==expected[k as keyof B2bRecord])||JSON.stringify(d.data().updatedAt)!==JSON.stringify(expected.updatedAt))throw Error('Registration changed. Reload before reviewing.');tx.update(r,{status,reviewedAt:serverTimestamp()});});const d=await getDocFromServer(r);if(!d.exists()||d.data().status!==status)throw Error('Review save could not be confirmed.');}
