// Staged, not imported by production. Receives only the signed-in customer's token.
export type SavedOrder={id:string;customerUid:string;customerEmail:string;customerPhone?:string;createdAt:string;paymentStatus:string;orderStatus:string;paymentMethod:'upi'|'cod'|'payu';totalAmount:number;subtotal?:number;shippingFee?:number;smallOrderDeliveryFee?:number;shoppingCharge?:number;currency:string;items:{name:string;quantity:number}[];trackingNumber?:string;courierName?:string};
export type OrderRequest={items:{productId:string;quantity:number;isWholesale?:boolean}[];customerName:string;customerPhone:string;shippingAddress:string;city:string;state:string;pincode:string;gstin?:string;currency:'INR';paymentMethod:'upi'|'cod'|'payu';expectedTotal:number};
export function orderClient({origin,identity,fetcher=fetch}:{origin:string;identity:()=>Promise<{uid:string;token:string}>;fetcher?:typeof fetch}){
 if(!/^https:\/\/[^/?#]+$/.test(origin))throw Error('Explicit HTTPS order service origin required');
 const call=async(path:string,method:string,body?:unknown,key?:string)=>{const user=await identity();if(!user.uid||!user.token)throw Error('Customer sign-in required');const res=await fetcher(origin+path,{method,headers:{Authorization:'Bearer '+user.token,...(body?{'Content-Type':'application/json'}:{}),...(key?{'Idempotency-Key':key}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});const result=await res.json();if((await identity()).uid!==user.uid)throw Error('Customer account changed; reload your orders before continuing');if(!res.ok)throw Error(result.error||'Order could not be confirmed');if(result.order&&(result.order.customerUid!==user.uid||!result.order.id||!['pending','paid'].includes(result.order.paymentStatus)||(path==='/api/orders/create'&&body&&((result.order.totalAmount!==(body as OrderRequest).expectedTotal)||(result.order.currency!=='INR')||(result.order.paymentMethod!==(body as OrderRequest).paymentMethod)))))throw Error('Saved order identity or payment state could not be confirmed');if(result.orders&&(!Array.isArray(result.orders)||result.orders.some((o:SavedOrder)=>o.customerUid!==user.uid)))throw Error('Order account mismatch');return result;};
 return {verificationProduct:()=>call('/api/orders/verification-product','POST',{}),payment:(orderId:string)=>call('/api/orders/payment?orderId='+encodeURIComponent(orderId),'GET'),paymentStatus:(orderId:string)=>call('/api/orders/payment-status','POST',{orderId}),create:(body:OrderRequest,key:string)=>call('/api/orders/create','POST',body,key),mine:(cursor?:string)=>call('/api/orders/mine'+(cursor?'?cursor='+encodeURIComponent(cursor):''),'GET'),recover:(key:string)=>call('/api/orders/recover','GET',undefined,key)};
}
// Store a random retry reference only, never customer details/token. Reconstruct payload
// only after user reviews it. A same-key conflicting body is rejected by server.
export function retryKey(uid:string,storage:Pick<Storage,'getItem'|'setItem'|'removeItem'>){const name='udecs-order-retry-'+uid;let key=storage.getItem(name);if(!key||!/^[-a-zA-Z0-9_]{32,128}$/.test(key)){key=crypto.randomUUID();storage.setItem(name,key);}return {key,confirmed:()=>storage.removeItem(name)};}
