export const backupCollections=['managementImportDrafts','managementImportedReferences','gstCalculatedDrafts','gstCalculatedAudit','operationsRegisters','operationsMatches','operationsAllocations','operationsAudit','workflowReviewDrafts','workflowReviewAudit']as const;
export type Backup={format:'udecs-private-backup-v1';createdAt:string;ownerUid:string;scope:'prepared-private-registers';collections:Record<string,Record<string,any>[]>;counts:Record<string,number>;digest:string};
export const normalized=(v:any):any=>Array.isArray(v)?v.map(normalized):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,normalized(v[k])])):v;
export async function digest(data:any){const raw=JSON.stringify(normalized(data));const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return Array.from(new Uint8Array(h)).map(n=>n.toString(16).padStart(2,'0')).join('');}
export async function makeBackup(ownerUid:string,collections:Backup['collections']):Promise<Backup>{const createdAt=new Date().toISOString(),counts=Object.fromEntries(backupCollections.map(k=>[k,collections[k]?.length??-1]));for(const k of backupCollections){if(!Array.isArray(collections[k])||collections[k].length>500)throw Error('Complete bounded source required: '+k);if(new Set(collections[k].map(r=>r.id)).size!==collections[k].length)throw Error('Duplicate IDs in '+k);for(const r of collections[k])if(typeof r.id!=='string'||!r.id||r.ownerUid!==ownerUid)throw Error('Record owner/ID mismatch: '+k);}validateBackupLinks(collections);const base={format:'udecs-private-backup-v1' as const,createdAt,ownerUid,scope:'prepared-private-registers' as const,collections,counts};return{...base,digest:await digest(base)};}
export function validateBackupLinks(collections:Backup['collections']){for(const[name,auditName]of[['gstCalculatedDrafts','gstCalculatedAudit'],['operationsRegisters','operationsAudit'],['operationsMatches','operationsAudit'],['workflowReviewDrafts','workflowReviewAudit']])for(const row of collections[name]||[]){const audit=collections[auditName]?.find(a=>a.id===row.auditId);if(!audit||JSON.stringify(normalized(audit.after))!==JSON.stringify(normalized(row)))throw Error('Current record/audit link mismatch: '+name+'/'+row.id);}for(const ref of collections.managementImportedReferences||[]){const draft=collections.managementImportDrafts?.find(d=>d.id===ref.draftId);if(!draft||draft.ownerUid!==ref.ownerUid||draft.target!==ref.target||JSON.stringify(normalized(draft.rows?.[ref.rowNumber]))!==JSON.stringify(normalized(ref.row)))throw Error('Imported reference/draft link mismatch.');}for(const allocation of collections.operationsAllocations||[]){const matches=(collections.operationsMatches||[]).filter(m=>m.bankAllocationId===allocation.id||m.targetAllocationId===allocation.id),sum=matches.reduce((n,m)=>n+(Number.isSafeInteger(m.amountPaise)?m.amountPaise:NaN),0);if(!Number.isSafeInteger(sum)||sum!==allocation.allocatedPaise||sum>allocation.maxPaise)throw Error('Allocation backup does not reconcile to matching history.');}}
export async function inspectBackup(text:string,ownerUid:string){if(text.length>10000000)throw Error('Backup exceeds10MB.');const data=JSON.parse(text)as Backup;if(data.format!=='udecs-private-backup-v1'||data.scope!=='prepared-private-registers'||data.ownerUid!==ownerUid||!/^\d{4}-/.test(data.createdAt)||Object.keys(data.collections||{}).some(k=>!backupCollections.includes(k as any)))throw Error('Unsupported scope/owner or backup format.');const{digest:expected,...base}=data;if(await digest(base)!==expected)throw Error('Checksum mismatch. Do not restore changed/damaged data.');const rebuilt=await makeBackup(ownerUid,data.collections);for(const k of backupCollections)if(data.counts[k]!==rebuilt.counts[k])throw Error('Count mismatch: '+k);return data;}
export function restorePlan(backup:Backup,current:Backup['collections']){return backupCollections.flatMap(name=>backup.collections[name].map(row=>{const found=current[name]?.find(r=>r.id===row.id);return{collection:name,id:row.id,status:!found?'missing-review':JSON.stringify(normalized(found))===JSON.stringify(normalized(row))?'identical-no-op':'conflict-stop',row};}));}
export function linkedDocument(url:string){const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||u.hash||u.search.length>1000||!['drive.google.com','docs.google.com','udecs.store'].includes(u.hostname))throw Error('Use an HTTPS document on approved Drive/Docs/UDECS domain, without credentials or fragment.');return u.href;}
export const accessMatrix=[{role:'Verified owner',read:'Own private prepared registers',write:'Reviewed audited drafts/references/allocations only',grant:'No automatic external sends/payments/deploys'},{role:'Other owner UID',read:'Denied for another owner’s prepared private records',write:'Denied on another owner’s records',grant:'No inherited private register access'},{role:'Employee / customer / unverified',read:'Denied for these prepared registers',write:'Denied',grant:'Existing operational permissions unchanged'}];
