import{decimal,realDate,rupees}from'../gst-computation-stage/model';
export type RegisterKind='fulfillment'|'return-refund'|'purchase'|'supplier'|'payable'|'amazon-settlement';
export type RegisterInput={kind:RegisterKind;source:string;reference:string;linkedReference:string;counterparty:string;date:string;dueDate:string;amount:string;status:string;evidence:string;note:string};
export const registerStatuses:Record<RegisterKind,string[]>={fulfillment:['pending-review','packed-reference','dispatch-reference','delivery-reference'],'return-refund':['return-request-reference','return-received-reference','refund-request-reference','refund-evidence-reference'],purchase:['purchase-invoice-reference','goods-received-reference'],supplier:['supplier-reference'],payable:['unpaid-reference','part-paid-reference','paid-evidence-reference'],'amazon-settlement':['settlement-reference']};
export function validateRegister(input:RegisterInput){if(!registerStatuses[input.kind]?.includes(input.status))throw Error('Unsupported register/status.');for(const key of ['source','reference','counterparty','evidence']as const)if(typeof input[key]!=='string'||!input[key].trim()||input[key].length>1000)throw Error('Source, unique reference, counterparty and evidence required.');if(typeof input.dueDate!=='string'||!realDate(input.date)||input.dueDate&&!realDate(input.dueDate))throw Error('Review record/due dates.');if([input.note,input.linkedReference,input.dueDate].some(v=>typeof v!=='string'))throw Error('Invalid reference fields.');if(input.note.length>2000||input.linkedReference.length>200)throw Error('Note/reference too long.');const amount=decimal(input.amount);if(['purchase','payable','amazon-settlement','return-refund'].includes(input.kind)&&amount===0n)throw Error('Positive reviewed amount required.');return{...input,amount:rupees(amount)};}
export type MatchSource={id:string;source:string;reference:string;date:string;amount:string;direction:'credit'|'debit';currency:'INR'};
export type MatchInput={bank:MatchSource;target:MatchSource;amount:string;evidence:string;reviewed:boolean};
export function validateMatch(m:MatchInput){if(m.reviewed!==true||!m.evidence.trim()||m.evidence.length>1000)throw Error('Review supporting evidence.');if(m.bank.source!=='bank-statement'||!['amazon-settlement','own-store-payment','supplier-payment','refund-payment'].includes(m.target.source))throw Error('Unsupported match sources.');if(!m.bank.id||!m.target.id||!m.bank.reference.trim()||!m.target.reference.trim()||!realDate(m.bank.date)||!realDate(m.target.date))throw Error('Actual source IDs/references/dates required.');if(m.bank.source==='bank-statement'&&(m.bank.direction!=='credit'||m.target.source!=='amazon-settlement'))throw Error('This stage matches Amazon credit settlements only.');if(m.bank.currency!=='INR'||m.target.currency!=='INR'||m.bank.direction!==m.target.direction)throw Error('Currency/direction mismatch.');const amount=decimal(m.amount),bank=decimal(m.bank.amount),target=decimal(m.target.amount);if(amount===0n||amount>bank||amount>target)throw Error('Allocation exceeds reviewed source amount.');return{...m,amount:rupees(amount)};}
export function remaining(source:MatchSource,matches:MatchInput[],side:'bank'|'target'){const total=decimal(source.amount),used=matches.filter(m=>m[side].id===source.id).reduce((n,m)=>n+decimal(m.amount),0n);if(used>total)throw Error('Overallocated source, reconciliation stopped.');return{amount:rupees(total-used),status:used===0n?'unreconciled':used===total?'fully-allocated-review':'partially-allocated-review'};}
export type TaxReconcileRow={id:string;source:string;period:string;gstin:string;invoice:string;taxable:string;tax:string;evidence:string};
export function reconcileTax(sales:TaxReconcileRow[],returns:TaxReconcileRow[]){const key=(r:TaxReconcileRow)=>[r.period,r.gstin,r.invoice].join('|'),a=new Map<string,TaxReconcileRow[]>(),b=new Map<string,TaxReconcileRow[]>();for(const[r,m]of [...sales.map(r=>[r,a]as const),...returns.map(r=>[r,b]as const)]){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(r.period)||!r.gstin||!r.invoice||!r.source||!r.evidence)throw Error('Reviewed tax source metadata required.');decimal(r.taxable);decimal(r.tax);m.set(key(r),[...(m.get(key(r))||[]),r]);}return[...new Set([...a.keys(),...b.keys()])].map(k=>{const x=a.get(k)||[],y=b.get(k)||[];return{key:k,sales:x,returns:y,status:x.length>1||y.length>1?'duplicate-conflict':!x.length?'return-only':!y.length?'sales-only':decimal(x[0].taxable)!==decimal(y[0].taxable)||decimal(x[0].tax)!==decimal(y[0].tax)?'amount-mismatch':'amounts-agree-not-filing-proof'};});}
