import React,{useEffect,useRef,useState}from'react';
import{Home,LayoutGrid,ShoppingCart,Package,Search,Plus,Minus,ArrowLeft,ArrowRight,Trash2,Check,WifiOff}from'lucide-react';
import{useStore}from'../context/StoreContext';import{Product,Order}from'../types';import{ProductDetailModal}from'../components/store/ProductDetailModal';import{CheckoutModal}from'../components/store/CheckoutModal';import{OrderTrackingModal}from'../components/store/OrderTrackingModal';import{wholesaleAvailability}from'../lib/wholesale';
export function CustomerApp(){
const{products,catalogStatus,cart,addToCart,removeFromCart,updateCartQty,cartCount,formatPrice,isOffline,language}=useStore();
const[slow,setSlow]=useState(false);useEffect(()=>{if(catalogStatus!=='loading'){setSlow(false);return}const t=setTimeout(()=>setSlow(true),15000);return()=>clearTimeout(t)},[catalogStatus]);
const[tab,setTab]=useState<'home'|'categories'|'cart'|'orders'>('home');const[category,setCategory]=useState('all');const[query,setQuery]=useState('');const[count,setCount]=useState(24);const[selected,setSelected]=useState<Product|null>(null);const[checkout,setCheckout]=useState(false);const[direct,setDirect]=useState<{product:Product;quantity:number;isWholesale:boolean}|null>(null);const[added,setAdded]=useState('');const[tracking,setTracking]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
useEffect(()=>{setCount(24)},[query,category]);useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
const shown=products.filter(p=>!(p as any).hidden&&!(p as any).gatewayVerification&&(category==='all'||p.category===category)&&[p.name,p.nameBn,p.sku].some(s=>String(s||'').toLowerCase().includes(query.toLowerCase())));
const choose=(t:typeof tab)=>{setTab(t);window.scrollTo({top:0,behavior:'smooth'})};const title=(p:Product)=>language==='bn'?p.nameBn:p.name;
const add=(p:Product)=>{if(!wholesaleAvailability(p))return;addToCart(p,1,false);setAdded(p.id);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setAdded(''),1400)};
const logo=<img className="app-logo" src="/6-udecs-app-logo.jpg" alt="UDECS for You"/>;
return <div className="customer-app"><header className="app-header">{tab==='cart'||tab==='orders'?<button aria-label="Back to shopping" onClick={()=>choose('home')}><ArrowLeft/></button>:logo}<div><h1>{tab==='cart'?'Your cart':tab==='orders'?'My orders':'UDECS for You'}</h1><p>{tab==='home'||tab==='categories'?'Your everyday shopping companion':'UDECS for You'}</p></div><button aria-label={`Open cart, ${cartCount} items`} onClick={()=>choose('cart')} className="header-cart"><ShoppingCart/>{cartCount>0&&<span>{cartCount}</span>}</button></header>
{isOffline&&<div className="app-notice" role="status"><WifiOff size={16}/>You're offline. Connect to refresh products and checkout.</div>}
{(tab==='home'||tab==='categories')&&<main className="app-main"><label className="app-search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products or SKU" aria-label="Search the full product catalog"/></label>{tab==='home'&&!query&&<div className="app-hero"><span>THE UNICK COLLECTION</span><h2>Little finds.<br/>Everyday joy.</h2><p>Explore kitchen, home and more.</p><img src="/6-udecs-app-logo.jpg" alt=""/></div>}<div className="app-section"><h2>{tab==='categories'?'Shop by category':'Explore the collection'}</h2>{catalogStatus==='ready'&&<span>{shown.length} products</span>}</div><div className="app-categories" aria-label="Product categories">{[['all','All products'],['kitchen','Kitchen'],['sports','Sports'],['industrial','Industrial'],['wholesale','Wholesale']].map(([id,label])=><button aria-pressed={category===id} className={category===id?'active':''} key={id} onClick={()=>setCategory(id)}>{label}</button>)}</div>{catalogStatus==='loading'&&<div className="app-state" role="status"><div className="app-spinner"/>{slow?<>The catalog is taking longer than usual. Check your connection or try again.<button className="app-btn outline" onClick={()=>window.location.reload()}>Try again</button></>:'Loading your collection...'}</div>}{catalogStatus==='error'&&<div className="app-state" role="alert">We couldn't refresh the catalog. {shown.length?'Previously loaded items may be out of date.':''}<button className="app-btn outline" onClick={()=>window.location.reload()}>Try again</button></div>}{catalogStatus==='ready'&&!shown.length&&<div className="app-state">No products match your search.<button className="app-btn outline" onClick={()=>{setQuery('');setCategory('all')}}>Clear filters</button></div>}<div className="app-grid">{shown.slice(0,count).map(p=><article className="app-card" key={p.id}><button className="app-photo" onClick={()=>setSelected(p)} aria-label={`View ${title(p)}`}>{p.imageUrl?<img src={p.imageUrl} alt={title(p)} loading="lazy"/>:<Package size={42}/>}</button><div className="app-card-body"><span className="app-sku">{p.sku}</span><button className="app-title" onClick={()=>setSelected(p)}>{title(p)}</button><div className="app-tax">{p.gstExtra?`+ GST ${p.gstRate}%`:'GST included'}</div><div className="app-row"><strong>{formatPrice(p.price)}</strong><button className="app-add" disabled={!wholesaleAvailability(p)} aria-label={`Add ${title(p)} to cart`} onClick={()=>add(p)}>{added===p.id?<Check size={20}/>:<Plus size={22}/>}</button></div>{!wholesaleAvailability(p)&&<span className="app-tax">Not available</span>}</div></article>)}</div>{shown.length>count&&<button className="app-btn outline app-more" onClick={()=>setCount(n=>n+24)}>Show more products</button>}</main>}
{tab==='cart'&&<main className="app-main"><div className="app-section"><h2>{cart.length} items selected</h2><span>Review your basket</span></div>{cart.length===0?<div className="app-state"><ShoppingCart size={40}/><h2>Your cart is empty</h2><button className="app-btn" onClick={()=>choose('home')}>Explore the collection</button></div>:<>{cart.map(({product:p,quantity,isWholesale})=><article className="app-cart-item" key={p.id}>{p.imageUrl?<img src={p.imageUrl} alt={title(p)}/>:<Package/>}<div><button className="app-title" onClick={()=>setSelected(p)}>{title(p)}</button><strong>{formatPrice((isWholesale||quantity>=p.minWholesaleQty?p.wholesalePrice:p.price)*quantity)}</strong><div className="app-row"><div className="app-qty"><button aria-label={`Reduce ${title(p)} quantity`} onClick={()=>updateCartQty(p.id,quantity-(p.quantityStep||1))}><Minus size={16}/></button><span>{quantity}</span><button aria-label={`Increase ${title(p)} quantity`} onClick={()=>updateCartQty(p.id,quantity+(p.quantityStep||1))}><Plus size={16}/></button></div><button className="app-remove" aria-label={`Remove ${title(p)}`} onClick={()=>removeFromCart(p.id)}><Trash2 size={18}/></button></div></div></article>)}<section className="app-panel"><h3>Before you checkout</h3><div><span>GST</span><span>Calculated at checkout</span></div><div><span>Delivery</span><span>Enter your pincode</span></div><p>Your final total is confirmed by the existing UDECS checkout. Review your address, applicable tax and delivery before placing the order.</p></section><button className="app-btn" disabled={isOffline} onClick={()=>{setDirect(null);setCheckout(true)}}>Continue to checkout <ArrowRight size={18}/></button></>}</main>}
{tab==='orders'&&<main className="app-main"><section className="app-panel app-state"><Package size={44}/><h2>Order status &amp; support</h2><p>Automatic shipment tracking is not connected yet. Our support team can check your order reference. No sample order or payment status is shown.</p><button className="app-btn" onClick={()=>setTracking(true)}>Get order support</button></section></main>}
<nav className="app-bottom" aria-label="Shopping navigation">{([['home',Home,'Home'],['categories',LayoutGrid,'Categories'],['cart',ShoppingCart,'Cart'],['orders',Package,'My orders']] as const).map(([id,Icon,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>choose(id)} className={tab===id?'active':''}><Icon size={22}/><span>{label}{id==='cart'&&cartCount?` (${cartCount})`:''}</span></button>)}</nav>
<ProductDetailModal product={selected} onClose={()=>setSelected(null)} onQuickCheckout={(product,quantity,isWholesale)=>{setSelected(null);setDirect({product,quantity,isWholesale});setCheckout(true)}}/>
<CheckoutModal isOpen={checkout} onClose={()=>{setCheckout(false);setDirect(null)}} directItem={direct} onOrderSuccess={(_order:Order)=>{}}/>
<OrderTrackingModal isOpen={tracking} onClose={()=>setTracking(false)}/><span className="app-announcement" aria-live="polite">{added?'Added to cart':''}</span>
</div>}
