import headers from './officialHeaders.json';import{computeInvoice,TaxInvoice,realDate,rupees}from'./model';
export type ReturnInvoice={invoice:TaxInvoice;ecoGstin:string;ecoName:string;ecoReviewed:boolean;classificationReviewed:boolean;recordSource:string;invoiceVerified:boolean;cessConfirmedZero:boolean};
export type DocSeries={from:string;to:string;total:number;cancelled:number;reviewed:boolean};
export type ExportSetup={gstin:string;period:string;frequency:'monthly'|'quarterly';periodStart:string;periodEnd:string;aatoBand:'up-to-5cr'|'over-5cr';applicabilityReviewed:boolean;completeSourcesReviewed:boolean;noOtherTablesConfirmed:boolean;roundingReviewed:boolean;documentSeries:DocSeries[]};
const official=headers as Record<string,string[]>;
const states:Record<string,string>={'01':'Jammu and Kashmir','02':'Himachal Pradesh','03':'Punjab','04':'Chandigarh','05':'Uttarakhand','06':'Haryana','07':'Delhi','08':'Rajasthan','09':'Uttar Pradesh','10':'Bihar','11':'Sikkim','12':'Arunachal Pradesh','13':'Nagaland','14':'Manipur','15':'Mizoram','16':'Tripura','17':'Meghalaya','18':'Assam','19':'West Bengal','20':'Jharkhand','21':'Odisha','22':'Chhattisgarh','23':'Madhya Pradesh','24':'Gujarat','26':'Dadra and Nagar Haveli and Daman and Diu','27':'Maharashtra','29':'Karnataka','30':'Goa','31':'Lakshadweep','32':'Kerala','33':'Tamil Nadu','34':'Puducherry','35':'Andaman and Nicobar Islands','36':'Telangana','37':'Andhra Pradesh','38':'Ladakh'};
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export function utilityDate(s:string){if(!realDate(s))throw Error('Invalid invoice date.');return s.slice(8,10)+'-'+months[Number(s.slice(5,7))-1]+'-'+s.slice(0,4);}
export function pos(s:string){if(!states[s])throw Error('Unsupported/current-state mapping missing: '+s);return s+'-'+states[s];}
export function gstCsv(name:string,rows:(string|number)[][]){const h=official[name];if(!h)throw Error('Official header not found.');if(rows.some(r=>r.length!==h.length))throw Error('CSV width does not match official template.');const cell=(v:string|number)=>{const s=String(v);if(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(s)||/^\s*[=@]/.test(s))throw Error('Unsafe text in return data.');return '"'+s.replace(/"/g,'""')+'"';};return [h,...rows].map(r=>r.map(cell).join(',')).join('\r\n')+'\r\n';}
function setup(s:ExportSetup){if(!s||!['monthly','quarterly'].includes(s.frequency)||!['up-to-5cr','over-5cr'].includes(s.aatoBand)||!Array.isArray(s.documentSeries))throw Error('Invalid return setup schema.');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(s.period)||!realDate(s.periodStart)||!realDate(s.periodEnd)||s.periodStart>s.periodEnd||!s.periodEnd.startsWith(s.period)||s.applicabilityReviewed!==true||s.completeSourcesReviewed!==true||s.noOtherTablesConfirmed!==true||s.roundingReviewed!==true)throw Error('Review period, taxpayer applicability, complete source coverage, rounding and unsupported tables.');const start=new Date(s.periodStart+'T12:00:00Z'),end=new Date(s.periodEnd+'T12:00:00Z');if(start.getUTCDate()!==1||new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()+1,0)).getUTCDate()!==end.getUTCDate())throw Error('Period must cover full calendar months.');const span=(end.getUTCFullYear()-start.getUTCFullYear())*12+end.getUTCMonth()-start.getUTCMonth()+1;if(s.frequency==='monthly'&&span!==1||s.frequency==='quarterly'&&(span!==3||![3,6,9,12].includes(end.getUTCMonth()+1)))throw Error('Period does not match monthly/calendar-quarter setting.');if(!s.documentSeries.length)throw Error('Reviewed document series required, including cancellations.');}
export function exportGstr1(s:ExportSetup,input:ReturnInvoice[]){setup(s);if(!input.length)throw Error('No verified invoices. Nil return workflow is separate; empty is not nil.');if(input.length>5000)throw Error('Split/review a smaller source set.');const files:Record<string,(string|number)[][]>={'b2b,sez,de.csv':[],'b2cl.csv':[],'b2cs.csv':[],'hsn(b2b).csv':[],'hsn(b2c).csv':[],'docs.csv':[],'eco.csv':[]};const b2cs=new Map<string,{p:string;rate:string;taxable:bigint;eco:string}>(),hsn=new Map<string,{file:string;hsn:string;description:string;uqc:string;qty:bigint;value:bigint;taxable:bigint;igst:bigint;cgst:bigint;sgst:bigint;rate:string}>(),eco=new Map<string,{name:string;net:bigint;igst:bigint;cgst:bigint;sgst:bigint}>(),seen=new Set<string>();let taxable=0n,tax=0n,gross=0n;
 for(const record of input){const d=record.invoice;if(record.classificationReviewed!==true||record.invoiceVerified!==true||!record.recordSource.trim()||record.cessConfirmedZero!==true)throw Error('Verified source invoice, tax classification and zero-cess confirmation required. Cess workflow not supported.');if(d.supplierGstin!==s.gstin||d.date<s.periodStart||d.date>s.periodEnd)throw Error('Invoice GSTIN/date outside selected return.');const identity=d.supplierGstin+'_'+d.number; if(seen.has(identity))throw Error('Duplicate invoice number in return source.');seen.add(identity);if(d.supplyType!=='ordinary-domestic'||d.reverseCharge)throw Error('Only ordinary domestic non-RCM invoices supported by this export. Special/credit/amendment workflow must be reviewed separately.');if(record.ecoReviewed!==true)throw Error('Review marketplace/ECO classification even when blank.');if(record.ecoGstin&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(record.ecoGstin))throw Error('Invalid ECO GSTIN.');if(record.ecoGstin&&!record.ecoName.trim())throw Error('ECO legal name required.');const c=computeInvoice(d);if(c.rates.some(r=>Number(r.rate)===0))throw Error('Zero/nil/exempt classification needs supported exempt-table treatment. This ordinary taxable export does not silently route it as B2B/B2CS.');if(c.rounding!==0n)throw Error('Invoice has non-zero rounding adjustment. Review supported allocation/return treatment before export.');const registered=d.recipientType==='registered';const threshold=s.period>='2024-08'?10000000n:25000000n;const large=!registered&&d.taxMode==='igst'&&c.total>threshold;
 for(const rate of c.rates){if(registered)files['b2b,sez,de.csv'].push([d.recipientGstin,d.recipientName,d.number,utilityDate(d.date),rupees(c.total),pos(d.placeOfSupply),'N','','Regular B2B',record.ecoGstin,rate.rate,rupees(rate.taxable),'0.00']);else if(large)files['b2cl.csv'].push([d.number,utilityDate(d.date),rupees(c.total),pos(d.placeOfSupply),'',rate.rate,rupees(rate.taxable),'0.00',record.ecoGstin]);else{const key=[d.placeOfSupply,rate.rate,record.ecoGstin].join('|'),b=b2cs.get(key)||{p:d.placeOfSupply,rate:rate.rate,taxable:0n,eco:record.ecoGstin};b.taxable+=rate.taxable;b2cs.set(key,b);}}
 for(const line of c.lines){if(s.aatoBand==='over-5cr'&&line.hsn.length<6||s.aatoBand==='up-to-5cr'&&line.hsn.length<4)throw Error('HSN length does not match reviewed AATO applicability.');const file=registered?'hsn(b2b).csv':'hsn(b2c).csv',key=[file,line.hsn,line.uqc,line.gstRate].join('|'),h=hsn.get(key)||{file,hsn:line.hsn,description:line.description,uqc:line.uqc,qty:0n,value:0n,taxable:0n,igst:0n,cgst:0n,sgst:0n,rate:line.gstRate};const [a,b='']=line.quantity.split('.');h.qty+=BigInt(a)*100n+BigInt(b.padEnd(2,'0'));h.value+=line.total;h.taxable+=line.taxable;h.igst+=line.igst;h.cgst+=line.cgst;h.sgst+=line.sgst;hsn.set(key,h);}
 if(record.ecoGstin){const e=eco.get(record.ecoGstin)||{name:record.ecoName,net:0n,igst:0n,cgst:0n,sgst:0n};if(e.name!==record.ecoName)throw Error('ECO GSTIN/name conflict.');e.net+=c.taxable;e.igst+=c.igst;e.cgst+=c.cgst;e.sgst+=c.sgst;eco.set(record.ecoGstin,e);}taxable+=c.taxable;tax+=c.cgst+c.sgst+c.igst;gross+=c.total;
 }
 for(const b of b2cs.values())files['b2cs.csv'].push([b.eco?'E':'OE',pos(b.p),b.rate,'',rupees(b.taxable),'0.00',b.eco]);
 for(const h of hsn.values())files[h.file].push([h.hsn,h.description,h.uqc,rupees(h.qty),rupees(h.value),rupees(h.taxable),rupees(h.igst),rupees(h.cgst),rupees(h.sgst),'0.00',h.rate]);
 let active=0;for(const series of s.documentSeries){if(series.reviewed!==true||!Number.isSafeInteger(series.total)||!Number.isSafeInteger(series.cancelled)||series.total<1||series.cancelled<0||series.cancelled>series.total||!series.from||!series.to||!/^[A-Za-z0-9/-]{1,16}$/.test(series.from)||!/^[A-Za-z0-9/-]{1,16}$/.test(series.to))throw Error('Review document series counts and endpoints.');active+=series.total-series.cancelled;files['docs.csv'].push(['Invoices for outward supply',series.from,series.to,series.total,series.cancelled]);}if(active!==input.length)throw Error('Active document count must reconcile to verified invoice count. Other documents need separate handling.');
 // Table14 category intentionally blocked pending exact enumeration and marketplace-specific tax treatment validation.
 if(eco.size)throw Error('ECO Table14 value mapping/settlement source validation pending. Marketplace tax export paused, not omitted.');
 return{version:'GST-Offline-V3.2.4',period:s.period,status:'reviewed_export_not_filed',files:Object.fromEntries(Object.entries(files).filter(([,r])=>r.length).map(([name,r])=>[name,gstCsv(name,r)])),summary:{invoices:input.length,taxable:rupees(taxable),tax:rupees(tax),gross:rupees(gross)},warnings:['Exact official headers matched. Actual Windows Offline Tool import and portal processing still require verification.','CSV imports into Offline Tool; utility generates JSON for portal upload. No filing occurs here.']};}
