import officialUqc from './officialUqc.json';
// Calculation drafts only. Rate/POS facts are supplied and reviewed, never inferred from category or state name.
export type TaxLine={id:string;description:string;hsn:string;uqc:string;quantity:string;unitPrice:string;priceMode:'exclusive'|'inclusive';gstRate:string;rateSource:string;rateValidFrom:string;rateValidTo:string;discount:string;charge:string;reviewed:boolean};
export type TaxInvoice={number:string;date:string;supplierGstin:string;supplierState:string;recipientName:string;recipientGstin:string;recipientType:'registered'|'unregistered';billingState:string;deliveryState:string;placeOfSupply:string;posReason:string;posReviewed:boolean;supplyType:'ordinary-domestic'|'bill-to-ship-to'|'special';taxMode:'cgst-sgst'|'igst';reverseCharge:boolean;lines:TaxLine[]};
export function realDate(s:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s;}
export function decimal(s:string,places=2):bigint{if(!/^\d+(?:\.\d{1,2})?$/.test(s))throw Error('Enter a non-negative decimal, at most two places. Missing is not zero.');const[a,b='']=s.split('.');const n=BigInt(a)*10n**BigInt(places)+BigInt(b.padEnd(places,'0'));if(n>100000000000n)throw Error('Amount or quantity too large.');return n;}
export function roundRatio(n:bigint,d:bigint):bigint{if(n<0n||d<=0n)throw Error('Invalid non-negative ratio.');return (n+d/2n)/d;}
export function rupees(p:bigint){return(p/100n).toString()+'.'+(p%100n).toString().padStart(2,'0');}
function state(s:string){return /^(0[1-9]|1\d|2[0-4679]|3[0-8])$/.test(s);}
export function computeInvoice(d:TaxInvoice){
 if(!d||!['registered','unregistered'].includes(d.recipientType)||!['ordinary-domestic','bill-to-ship-to','special'].includes(d.supplyType)||!['cgst-sgst','igst'].includes(d.taxMode)||typeof d.reverseCharge!=='boolean'||!Array.isArray(d.lines))throw Error('Invalid invoice schema/type.');
 if(!/^[A-Za-z0-9/-]{1,16}$/.test(d.number)||d.number==='0'||!realDate(d.date))throw Error('Review invoice number and date.');
 if(!/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(d.supplierGstin)||!state(d.supplierState)||d.supplierGstin.slice(0,2)!==d.supplierState)throw Error('Supplier GSTIN/state required and must agree. Registration not verified by syntax.');
 if(!d.recipientName.trim()||!state(d.placeOfSupply)||!state(d.billingState)||!state(d.deliveryState)||d.posReviewed!==true||!d.posReason.trim())throw Error('Review recipient, billing/delivery states and evidenced place-of-supply decision.');
 if(d.recipientType==='registered'&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(d.recipientGstin))throw Error('Registered recipient GSTIN required.');if(d.recipientType==='unregistered'&&d.recipientGstin)throw Error('Recipient type conflicts with GSTIN.');
 if(d.supplyType==='special'||d.reverseCharge)throw Error('Special supply/reverse charge needs a separate reviewed tax workflow. No ordinary calculator result.');
 if(d.taxMode==='cgst-sgst'&&d.supplierState!==d.placeOfSupply||d.taxMode==='igst'&&d.supplierState===d.placeOfSupply)throw Error('Tax split conflicts with supplier/POS states. Special exceptions are not supported here.');
 if(!d.lines.length||d.lines.length>200||new Set(d.lines.map(l=>l.id)).size!==d.lines.length)throw Error('Use1-200uniquely identified lines.');
 const rates=new Map<string,{taxable:bigint;cgst:bigint;sgst:bigint;igst:bigint;rounding:bigint}>();
 const lines=d.lines.map(l=>{if(!['inclusive','exclusive'].includes(l.priceMode)||!officialUqc.includes(l.uqc)||!l.id.trim())throw Error('Review line identity, official UQC and price mode.');if(!l.description.trim()||!/^\d{4,8}$/.test(l.hsn)||!l.uqc.trim()||l.reviewed!==true||!l.rateSource.trim()||!realDate(l.rateValidFrom)||d.date<l.rateValidFrom||l.rateValidTo&&(!realDate(l.rateValidTo)||d.date>l.rateValidTo))throw Error('Line '+l.id+': HSN/UQC/rate source/effective dates and review required.');const qty=decimal(l.quantity),price=decimal(l.unitPrice),rate=decimal(l.gstRate);if(qty===0n||rate>10000n)throw Error('Positive quantity and reviewed GST0-100%required.');const gross=roundRatio(qty*price,100n),discount=decimal(l.discount),charge=decimal(l.charge);if(discount>gross)throw Error('Line discount exceeds value.');const base=gross-discount+charge;
 // Discount/charge are reviewed invoice-value adjustments in the same price mode as this line. Post-sale credit notes are not inferred.
 const taxable=l.priceMode==='inclusive'?roundRatio(base*10000n,10000n+rate):base;let cgst=0n,sgst=0n,igst=0n;if(d.taxMode==='igst')igst=l.priceMode==='inclusive'?base-taxable:roundRatio(taxable*rate,10000n);else{cgst=roundRatio(taxable*rate,20000n);sgst=cgst;}const value=taxable+cgst+sgst+igst,rounding=l.priceMode==='inclusive'?base-value:0n;const key=rupees(rate);const bucket=rates.get(key)||{taxable:0n,cgst:0n,sgst:0n,igst:0n,rounding:0n};bucket.taxable+=taxable;bucket.cgst+=cgst;bucket.sgst+=sgst;bucket.igst+=igst;bucket.rounding+=rounding;rates.set(key,bucket);return {...l,gstRate:key,taxable,cgst,sgst,igst,rounding,total:value+rounding};});const sum=(key:'taxable'|'cgst'|'sgst'|'igst'|'rounding'|'total')=>lines.reduce((n,l)=>n+l[key],0n);return{lines,rates:[...rates].map(([rate,v])=>({rate,...v})),taxable:sum('taxable'),cgst:sum('cgst'),sgst:sum('sgst'),igst:sum('igst'),rounding:sum('rounding'),total:sum('total'),status:'calculation_draft_not_filed' as const};}
