CREATE TABLE IF NOT EXISTS quotationDrafts(id TEXT PRIMARY KEY,owner TEXT NOT NULL,revision INTEGER NOT NULL,data TEXT NOT NULL,updatedAt TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS quotationPublications(id TEXT PRIMARY KEY,owner TEXT NOT NULL,draftId TEXT NOT NULL,revision INTEGER NOT NULL,tokenHash TEXT NOT NULL UNIQUE,pdf BLOB NOT NULL,pdfHash TEXT NOT NULL,summary TEXT NOT NULL,expiresAt INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,createdAt TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS quotationOwner ON quotationPublications(owner,createdAt);
