export type QuoteCustomer={business:string;contact:string;phone:string;email:string;gstin:string;billing:string;shipping:string;state:string;postcode:string;country:string};
export type QuoteItem={id:string;sku:string;name:string;hsn:string;unit:string;quantity:string;price:string;gst:string;minimum:number;step:number};
export type QuoteDraft={id:string;revision:number;number:string;date:string;validUntil:string;customer:QuoteCustomer;items:QuoteItem[];taxMode:'exclusive'|'inclusive';taxType:''|'cgst-sgst'|'igst';terms:string;freight:string;discount:string;sourceRfqId?:string};
export const blankCustomer=():QuoteCustomer=>({business:'',contact:'',phone:'',email:'',gstin:'',billing:'',shipping:'',state:'',postcode:'',country:'India'});
export function decimal(value:string,places=2){if(!/^\d+(?:\.\d{1,2})?$/.test(value.trim()))throw Error('Use a non-negative amount with at most two decimals.');const [n,d='']=value.split('.');const v=Number(n)*10**places+Number(d.padEnd(places,'0'));if(!Number.isSafeInteger(v)||v>100000000000)throw Error('Amount is too large.');return v}
export function totals(d:Pick<QuoteDraft,'items'|'freight'|'discount'|'taxMode'>){let net=0,tax=0;const lines=d.items.map(i=>{if(!/^\d+$/.test(i.quantity)||+i.quantity<=0||+i.quantity>1000000)throw Error('Quantity must be a positive whole number.');const q=+i.quantity,p=decimal(i.price),rate=decimal(i.gst);if(rate>10000)throw Error('GST rate must be between0and100.');if(q<i.minimum||q%i.step!==0)throw Error('Quantity does not meet catalog minimum / step.');const amount=q*p;if(!Number.isSafeInteger(amount)||amount>100000000000)throw Error('Line total too large.');const n=d.taxMode==='inclusive'?Math.round(amount*10000/(10000+rate)):amount;const t=d.taxMode==='inclusive'?amount-n:Math.round(n*rate/10000);net+=n;tax+=t;return {net:n,tax:t,total:n+t}});const freight=decimal(d.freight),discount=decimal(d.discount);if(discount>net+tax)throw Error('Discount exceeds items total.');return {net,tax,freight,discount,total:net+tax+freight-discount,lines}}
export const inr=(paise:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(paise/100);
export function verifyQuote(d:QuoteDraft,final=false){const c=d.customer;if(!d.id||!Number.isInteger(d.revision)||d.revision<1)throw Error('Invalid quotation identity.');for(const [k,v]of Object.entries(c))if(typeof v!=='string'||v.length>1000)throw Error('Customer field too long: '+k);if(!c.business.trim())throw Error('Business name is required.');if(c.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c.email))throw Error('Check customer email.');if(c.gstin&&!/^\d{2}[A-Z]{5}\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(c.gstin))throw Error('Check GSTIN or leave it blank if not supplied.');if(d.items.length<1||d.items.length>50)throw Error('Use1to50items.');if(d.number.length>80||d.terms.length>2500)throw Error('Number or terms too long.');for(const i of d.items){if(!i.name.trim()||i.name.length>300||i.hsn.length>20||i.sku.length>100||i.unit.length>30)throw Error('Check item details.');if(!Number.isInteger(i.minimum)||i.minimum<1||!Number.isInteger(i.step)||i.step<1)throw Error('Check catalog quantity rules.')}if(!validDate(d.date)||!validDate(d.validUntil)||d.validUntil<d.date)throw Error('Check quotation date and valid-through date.');if(final){if(!c.contact||!c.phone||!c.billing||!c.shipping||!c.state||!c.postcode||!c.country)throw Error('Complete and review customer/contact/address fields before publication.');if(!d.taxType)throw Error('Confirm place of supply and CGST/SGST or IGST.');if(d.items.some(i=>!i.hsn.trim()))throw Error('Review HSN for every item before publication.');if(!d.terms.trim())throw Error('Review terms before publication.')}return totals(d)}
export const customerColumns=['business','contact','phone','email','gstin','billing','shipping','state','postcode','country'] as const;
export function mappedCustomer(row:unknown[],mapping:Record<string,number>){const c=blankCustomer();for(const key of customerColumns){const v=row[mapping[key]];if(v!==undefined&&v!==null){if(typeof v==='object')throw Error('Formula or structured cell needs a reviewed plain-text value.');c[key]=String(v).trim();if(c[key].length>1000)throw Error('Imported field too long.')}}return c}

export function validDate(s:string){if(!/^\d{4}-\d\d-\d\d$/.test(s))return false;const d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s}
