import {jsPDF} from 'jspdf';import {CompanyInfo}from'../types';import{QuoteDraft,verifyQuote,inr}from'./model';
export async function quotationPdf(d:QuoteDraft,company:CompanyInfo,final=false){const sums=verifyQuote(d,final);const base=new Image();base.src='./quotation-letterhead.jpg';await base.decode();const doc=new jsPDF({unit:'pt',format:'a4'});let page=0,canvas:HTMLCanvasElement,c:CanvasRenderingContext2D,y=0;
function newPage(){if(page)doc.addPage();page++;canvas=document.createElement('canvas');canvas.width=1190;canvas.height=1684;c=canvas.getContext('2d')!;c.drawImage(base,0,0,1190,1684);c.scale(2,2);y=130;text('B2B CUSTOMER QUOTATION',50,y,18,true);y+=22;text((final?'Reviewed quotation':'DRAFT - review before sharing')+' | '+d.number+' | Revision '+d.revision,50,y,9,true);y+=20;text('Date: '+d.date+' | Valid through: '+d.validUntil,50,y,9);y+=25}
function text(t:string,x:number,at:number,size=10,bold=false,right=false){c.font=(bold?'bold ':'')+size+'px Arial';c.fillStyle='#183858';c.textAlign=right?'right':'left';c.fillText(t,x,at)}
function wrap(t:string,x:number,width:number,size=10){c.font=size+'px Arial';const words=t.replace(/\r/g,'').split(/\s+/);let line='';const lines:string[]=[];for(const word of words){if(c.measureText(word).width>width){if(line){lines.push(line);line=''}let segment='';for(const ch of word){if(c.measureText(segment+ch).width>width){lines.push(segment);segment=''}segment+=ch}line=segment;continue}if(c.measureText((line?line+' ':'')+word).width>width){lines.push(line);line=word}else line+=(line?' ':'')+word}if(line)lines.push(line);return lines}
function flush(){text('Quotation only. Not a tax invoice. No stock reservation or payment collected.',50,765,7.8);text('Page '+page,545,805,7,false,true);doc.addImage(canvas.toDataURL('image/jpeg',.70),'JPEG',0,0,595.28,841.89,undefined,'FAST')}
function block(t:string,bold=false){const lines=wrap(t,50,495,9.5);for(const line of lines){if(y>738){flush();newPage()}text(line,50,y,9.5,bold);y+=14}y+=5}
newPage();block('Seller: '+company.legalName+' | GSTIN: '+(company.gstin||'Not supplied'));block('Registered address: '+(company.address||'Not supplied'));block('Prepared for: '+d.customer.business+' | Contact: '+(d.customer.contact||'Not supplied'),true);block('Phone: '+(d.customer.phone||'Not supplied')+' | Email: '+(d.customer.email||'Not supplied'));block('GSTIN: '+(d.customer.gstin||'Not supplied')+' | State: '+(d.customer.state||'Not supplied'));block('Bill to: '+(d.customer.billing||'Not supplied')+' | '+d.customer.postcode+' | '+d.customer.country);block('Ship to: '+(d.customer.shipping||'Not supplied'));
function tableHead(){c.fillStyle='#edf2f7';c.fillRect(50,y-10,495,22);for(const [x,t]of[[60,'Description / HSN'],[301,'Qty'],[338,'Unit price'],[410,'GST'],[492,'Line total']] as const)text(t,x,y+4,8,true);y+=27}tableHead();d.items.forEach((i,index)=>{const lines=wrap(i.name+' | '+i.sku+' | HSN '+(i.hsn||'unverified')+' | '+i.unit,60,228,9);const h=lines.length*13+22;if(y+h>730){flush();newPage();tableHead()}lines.forEach((l,n)=>text(l,60,y+n*13,9));text(i.quantity,301,y,8);text(inr(Number(i.price)*100),338,y,8);text(i.gst+'%',410,y,8);text(inr(sums.lines[index].total),540,y,8,false,true);y+=h;c.strokeStyle='#d6e1ec';c.beginPath();c.moveTo(50,y-5);c.lineTo(545,y-5);c.stroke();y+=9});y+=14;
const gstLines=d.taxType==='cgst-sgst'?[['CGST',Math.floor(sums.tax/2)],['SGST',sums.tax-Math.floor(sums.tax/2)]]:d.taxType==='igst'?[['IGST',sums.tax]]:[['GST (supply state unconfirmed)',sums.tax]];for(const [label,amount]of[['Taxable items',sums.net],...gstLines,['Freight (reviewed final charge)',sums.freight],['After-tax adjustment / discount',-sums.discount],['Total',sums.total]] as [string,number][]){if(y>715){flush();newPage()}text(label,285,y,9,label==='Total');text(inr(amount),540,y,10,label==='Total',true);y+=22}block('Price basis: '+d.taxMode+' GST. Freight and after-tax adjustments are separately reviewed; no automatic tax assumption.');block('Terms: '+(d.terms||'Not supplied - draft only'));flush();const blob=doc.output('blob');if(blob.size>1000000)throw Error('PDF exceeds free-share1MB limit. Reduce item count or terms; local draft remains intact.');return blob}
