import React,{useEffect,useRef,useState} from 'react';
import {doc,getDocFromServer} from 'firebase/firestore';
import {db} from '../../firebase/config';
import {requireListingOwner} from '../../firebase/productListingService';
import {getApiUrl} from '../../services/api';
type Check={label:string;status:'checking'|'verified'|'failed'|'unverified';evidence:string;at:string;action?:string};
const initial:Check[]=[{label:'API service',status:'unverified',evidence:'Not checked in this session.',at:''},{label:'Catalog sample',status:'unverified',evidence:'Not checked in this session.',at:''},{label:'Order alerts',status:'unverified',evidence:'The hourly watch runs separately. This panel has no authenticated log feed yet; no delivery claim.',at:''},{label:'Deployment',status:'unverified',evidence:'This panel is loaded in your browser. Deployment success and installed-app version need separate verification.',at:''}];
export function AdminSoftwareHealth(){const [checks,setChecks]=useState<Check[]>(initial),[busy,setBusy]=useState(false),[report,setReport]=useState(''),[retried,setRetried]=useState(false);const run=useRef(0);let owner=false;try{requireListingOwner();owner=true;}catch{}
 useEffect(()=>()=>{run.current++;},[]);
 async function check(recovery=false){if(busy||!owner)return;const version=++run.current,uid=requireListingOwner();setBusy(true);setReport('Checking read-only evidence. No orders, payments or records will change.');const at=new Date().toLocaleString();
 const rows=[...initial];
 await Promise.all([ (async()=>{try{const r=await fetch(getApiUrl('/health'),{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok||!r.headers.get('content-type')?.includes('application/json'))throw Error();const d=await r.json();if(d.status!=='ok')throw Error();rows[0]={label:'API service',status:'verified',evidence:'Live /health returned HTTP '+r.status+' and status ok. This does not prove checkout, payment or email delivery.',at};}catch{rows[0]={label:'API service',status:'failed',evidence:'API check did not return a verified health response. Network, routing or service failure remains possible.',at,action:'A fresh read can recover a transient network failure. Repeated failure needs diagnosis, not repeated requests.'};}})(),(async()=>{try{const shard=await getDocFromServer(doc(db,'catalogSearchChunks','00'));if(!shard.exists()||!Array.isArray(shard.data().entries)||shard.data().version!==1)throw Error();const entries=shard.data().entries,id=entries.find((e:any)=>typeof e.id==='string')?.id;if(!id)throw Error();const sample=await getDocFromServer(doc(db,'products',id));if(!sample.exists())throw Error();rows[1]={label:'Catalog sample',status:'verified',evidence:'Server confirmed search chunk 00 ('+entries.length+' entries) and one indexed product. Full catalog, stock and checkout are not audited by this sample.',at};}catch{rows[1]={label:'Catalog sample',status:'failed',evidence:'Search chunk or sample product could not be confirmed from the server. Quota, permissions, network or index inconsistency remain possible; root cause is not established.',at,action:'Inspect Firebase quota and access evidence before changing catalog data.'};}})()]);
 if(version!==run.current)return;try{if(requireListingOwner()!==uid)return;setChecks(rows);setReport(recovery?'One safe read-only retry completed. No business records changed.':'Read-only checks completed. Verified means only the evidence described below, not full software health.');}catch{setChecks(initial);setReport('Owner changed. Sign in again before checking.');}finally{setBusy(false);}
 }
 return <section className="max-w-5xl mx-auto space-y-5 text-slate-800"><header><h2 className="text-2xl font-bold">Software Health</h2><p className="mt-2">Monitor, diagnose, review repairs. Owner-only checks with evidence, not a promise that every problem can fix itself.</p></header>{!owner?<p className="p-4 bg-amber-50 border rounded-xl">Sign in with your verified owner Google account. Staff cannot run these checks.</p>:<><div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>{setRetried(false);void check();}} className="bg-blue-800 text-white rounded-lg px-5 py-3 disabled:opacity-50">{busy?'Checking...':'Run safe health check'}</button><button disabled={busy||retried||!checks.some(c=>c.status==='failed')} onClick={()=>{setRetried(true);void check(true);}} className="border rounded-lg px-5 py-3 disabled:opacity-50">Retry failed reads once</button></div><p role="status" className="bg-blue-50 border rounded-xl p-4">{report||'No automatic database reads on page load. Run a check when needed; this avoids using free quota just to watch the dashboard.'}</p><div className="grid md:grid-cols-2 gap-4">{checks.map(c=><article key={c.label} className="border rounded-xl p-4 bg-white space-y-2"><h3 className="font-bold text-lg">{c.label}</h3><p className={c.status==='verified'?'text-emerald-800 font-semibold':c.status==='failed'?'text-red-700 font-semibold':'text-slate-600 font-semibold'}>{c.status==='verified'?'Verified read':c.status==='failed'?'Needs attention':'Not verified'}</p><p className="text-sm break-words">{c.evidence}</p>{c.at&&<p className="text-xs text-slate-500">Checked: {c.at}. No background refresh.</p>}{c.action&&<p className="text-sm bg-amber-50 p-3 rounded">{c.action}</p>}</article>)}</div></>}
 <div className="border rounded-xl p-4 bg-slate-50 space-y-3"><h3 className="font-bold">Repair boundaries</h3><p className="text-sm">Safe in this panel: refresh a read and retry once. Source fixes can be investigated, tested and reported separately. This first version does not edit software automatically.</p><p className="text-sm">Payments, orders, GST, customer/HR data, access rules, schema and paid services require separate owner review. A failed check never authorizes a data change.</p><p className="text-sm">Existing daily software review and hourly order-alert watch continue separately. Their results are not yet synced here; continuous in-panel monitoring and repair history are still pending.</p><div className="flex flex-wrap gap-4 text-blue-800 underline text-sm"><a href="https://dash.cloudflare.com/bfa14054934d0f067511f26979c971d4/workers/services/view/udecs-orders-api/production/observability" target="_blank" rel="noreferrer">Order-alert logs</a><a href="https://github.com/sksaharukhossain1996-dot/udecs-website/actions" target="_blank" rel="noreferrer">Website builds</a></div></div></section>;
                                     }
