import React,{useState,useEffect} from 'react';
import {useStore} from '../../context/StoreContext';
import {subscribeEmployees} from '../../firebase/employeeService';
import {subscribeAttendance,saveAttendance,CloudAttendance} from '../../firebase/attendanceService';
import type {Employee} from '../../types';
const indiaToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function AttendanceCalendar(){
 const {firebaseUser}=useStore();const [month,setMonth]=useState(()=>indiaToday().slice(0,7)),[employees,setEmployees]=useState<Employee[]>([]),[rows,setRows]=useState<CloudAttendance[]>([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState<{employee:Employee;date:string}|null>(null),[status,setStatus]=useState<CloudAttendance['status']>('present'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{setEmployees([]);setSelected(null);try{return subscribeEmployees(setEmployees,e=>setError(e.message))}catch(e){setError((e as Error).message)}},[firebaseUser?.uid]);
 useEffect(()=>{setRows([]);setLoaded(false);setSelected(null);setError('');try{return subscribeAttendance(month,r=>{setRows(r);setLoaded(true)},e=>{setError(e.message);setLoaded(false)})}catch(e){setError((e as Error).message)}},[month,firebaseUser?.uid]);
 const parts=month.split('-').map(Number),days=new Date(parts[0],parts[1],0).getDate();
 return <section className="mt-6 p-4 bg-white border rounded-lg space-y-4"><h2 className="text-xl font-bold">Cloud attendance calendar</h2><p className="text-sm">Real cloud employee roster. Unmarked days are blank, not absent. No salary calculation or payment confirmation. Calendar dates use India time.</p><label className="block">Month<input className="ml-3 border rounded p-2" type="month" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value)}}/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status">{notice}</p>}{!loaded?<p>Loading server attendance. Marking unavailable until confirmed.</p>:null}<div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr><th className="p-2 text-left">Employee</th>{Array.from({length:days},(_,i)=><th key={i} className="p-2 border">{i+1}</th>)}</tr></thead><tbody>{employees.map(employee=><tr key={employee.id}><th className="p-2 text-left min-w-40">{employee.name}</th>{Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0'),record=rows.find(r=>r.employeeId===employee.id&&r.date===date);return <td key={date} className="border p-1"><button className="w-12 h-10 rounded border text-xs" disabled={!loaded||busy} title={`${employee.name} ${date}: ${record?.status||'Unmarked'}`} onClick={()=>{setSelected({employee,date});setStatus(record?.status||'present');setNote(record?.note||'');setNotice('')}}>{record?{present:'P','half-day':'H',absent:'A',leave:'L'}[record.status]:'-'}</button></td>})}</tr>)}</tbody></table></div><p className="text-xs">P = Present · H = Half day · A = Absent · L = Leave · - = Unmarked</p>{loaded&&employees.length===0&&<p>No cloud employees found.</p>}{selected&&<div className="p-4 border rounded space-y-3" role="dialog" aria-label="Review attendance"><h3 className="font-bold">{selected.employee.name} - {selected.date}</h3><label className="block">Status<select className="ml-2 border p-2" value={status} onChange={e=>setStatus(e.target.value as CloudAttendance['status'])}><option value="present">Present</option><option value="half-day">Half day</option><option value="absent">Absent</option><option value="leave">Leave</option></select></label><label className="block">Note (optional)<textarea className="block w-full border p-2" maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><button disabled={busy} className="p-3 bg-[#183758] text-white rounded" onClick={async()=>{setBusy(true);setError('');try{await saveAttendance(selected.employee.id,selected.employee.name,selected.date,status,note);setSelected(null);setNotice('Attendance saved and checked on server.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Saving...':'Save attendance'}</button><button disabled={busy} className="p-3 border rounded ml-2" onClick={()=>setSelected(null)}>Cancel</button></div>}</section>;
}
