import{employeePreflight}from'../../import-stage/preflight';
import {ImportPanel} from '../../import-stage/ImportPanel';import {specs} from '../../import-stage/model';import {getDocsFromServer,collection} from 'firebase/firestore';import {db} from '../../firebase/config';import {requireHROwner} from '../../firebase/employeeService';
import {useLocalBack} from '../../navigation/ManagementBack';
import React,{useEffect,useState}from'react';
import{subscribeEmployees,createEmployee,removeEmployee}from'../../firebase/employeeService';
import{checkEmployeeDuplicate}from'../../lib/employeeManagement';
import{useStore}from'../../context/StoreContext';
import{validateEmployee,EmployeeForm}from'../../lib/employeeManagement';
import type{Employee}from'../../types';
import{ADMIN_EMAILS}from'../../firebase/firestoreService';
const blank:EmployeeForm={name:'',email:'',phone:'',designation:'',department:'',baseSalary:'',joiningDate:'',role:'inventory'};
export function EmployeeActions(){
 const{firebaseUser}=useStore();
 const[employees,setEmployees]=useState<Employee[]>([]),[loaded,setLoaded]=useState(false);
 const[form,setForm]=useState(blank),[open,setOpen]=useState(false),[review,setReview]=useState<Employee|null>(null),[remove,setRemove]=useState<Employee|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);useLocalBack(open||!!review||!!remove,'Back to employees',()=>{if(busy)return;if(remove){setRemove(null);return}if(review){setReview(null);return}setOpen(false)});
 const owner=!!firebaseUser?.emailVerified&&ADMIN_EMAILS.includes((firebaseUser.email||'').toLowerCase());
 useEffect(()=>{setEmployees([]);setLoaded(false);if(!owner)return;return subscribeEmployees(rows=>{setEmployees(rows);setLoaded(true);},e=>{setEmployees([]);setLoaded(false);setError(e.message);});},[firebaseUser?.uid,owner]);
 useEffect(()=>{setOpen(false);setReview(null);setRemove(null);setForm(blank);setError('');setNotice('');},[firebaseUser?.uid]);
 if(!owner)return <p className="p-4 border rounded-lg">Employee records are available to the signed-in owner only.</p>;
 const field=(key:keyof EmployeeForm,label:string,type='text',optional=false)=><label key={key} className="block text-sm font-semibold">{label}{optional?' (optional)':''}<input type={type} required={!optional} value={form[key]} onChange={e=>{setForm({...form,[key]:e.target.value});setError('');}} className="mt-1 mb-3 block w-full rounded border p-3 bg-white text-slate-900" maxLength={type==='text'?120:undefined}/></label>;
 return <section className="p-4 bg-white border rounded-lg space-y-4">
 <h2 className="text-lg font-bold">Add / Delete Employee</h2><ImportPanel key={firebaseUser?.uid} spec={specs.employees} disabled={!loaded||busy} validate={r=>{try{validateEmployee(r as EmployeeForm);return [];}catch(e){return [(e as Error).message];}}} commit={async(imported,ids,progress)=>{const uid=requireHROwner();const fresh=await getDocsFromServer(collection(db,"hrEmployees"));const existing=fresh.docs.map(d=>({...d.data(),id:d.id} as Employee));const prepared=employeePreflight(imported,ids,existing);for(let i=0;i<imported.length;i++){if(requireHROwner()!==uid)throw Error("Account changed. Import stopped.");const e=prepared[i];const same=existing.find(x=>x.id===e.id);if(!same)checkEmployeeDuplicate(existing,e);await createEmployee(e);if(!same)existing.push(e);progress(i+1);}setNotice("Reviewed employee import saved. No login access granted.");}}/>
 <p className="text-sm text-amber-900 bg-amber-50 p-3 rounded">Cloud employee directory: same list on phone and laptop when signed in as owner. Adding an employee does not grant portal login access. Existing browser attendance/payroll records are not migrated or changed.</p>
 {error&&<p role="alert" className="text-red-700">{error}</p>}{notice&&<p role="status" className="text-green-800">{notice}</p>}
 <button disabled={!loaded||busy} onClick={()=>{setOpen(!open);setReview(null);setError('');setNotice('');}} className="bg-[#182620] text-white rounded px-4 py-3">{open?'← Back to employees':'Add Employee'}</button>
 {open&&!review&&<form onSubmit={e=>{e.preventDefault();try{setReview({...validateEmployee(form),id:'EMP-'+crypto.randomUUID()});setError('');}catch(e){setError((e as Error).message);}}} className="grid sm:grid-cols-2 gap-x-4">
 {field('name','Employee name')}{field('phone','Phone','tel',true)}{field('email','Email','email',true)}{field('designation','Designation')}{field('department','Department')}{field('baseSalary','Monthly base salary (Rs)','number')}{field('joiningDate','Joining date','date')}
 <label className="block text-sm font-semibold">Staff role<select className="block border rounded p-3 w-full mt-1" value={form.role} onChange={e=>setForm({...form,role:e.target.value as Employee['role']})}><option value="inventory">Inventory</option><option value="manager">Manager</option><option value="accountant">Accounts</option></select></label>
 <button type="submit" className="rounded bg-[#182620] text-white px-4 py-3">Review employee</button></form>}
 {review&&<div className="p-4 border rounded space-y-3"><h3 className="font-bold">Review: {review.name}</h3><p className="break-words">{review.designation} · {review.department}<br/>{review.email||'No email'} · {review.phone||'No phone'}<br/>Base salary Rs{review.baseSalary}/month · Joining {review.joiningDate}<br/>Role: {review.role} · No portal login access</p><div className="flex flex-wrap gap-3"><button disabled={busy} className="bg-[#182620] text-white p-3 rounded" onClick={async()=>{setBusy(true);try{checkEmployeeDuplicate(employees,review);await createEmployee(review);setNotice('Employee saved to cloud.');setReview(null);setForm(blank);setOpen(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Save Employee</button><button disabled={busy} onClick={()=>setReview(null)} className="border p-3 rounded">Back to edit</button></div></div>}
 <div className="space-y-2">{!loaded?<p>Loading cloud list. Changes unavailable until server data arrives.</p>:employees.length===0?<p>No cloud employees yet. Add your first employee above.</p>:null}{employees.map(e=><div key={e.id} className="border-b py-3 flex gap-3 items-center"><div className="min-w-0 flex-1"><strong className="break-words">{e.name}</strong><p className="text-sm break-words">{e.employeeCode||e.id} · {e.designation||e.role}</p></div>{e.role==='admin'||ADMIN_EMAILS.includes(e.email.toLowerCase())?<span className="text-xs">Owner protected</span>:<button className="border border-red-200 text-red-700 rounded p-3" onClick={()=>{setRemove(e);setError('');setNotice('');}}>Delete</button>}</div>)}</div>
 {remove&&<div role="dialog" aria-label="Confirm employee deletion" className="border border-red-300 bg-red-50 p-4 rounded space-y-3"><h3 className="font-bold break-words">Delete {remove.name}?</h3><p className="text-sm break-words">Employee ID: {remove.employeeCode||remove.id}. The employee will be removed from the cloud directory. Existing attendance and salary slips stay. This cannot be undone here.</p><div className="flex flex-wrap gap-3"><button disabled={busy} className="bg-red-700 text-white p-3 rounded" onClick={async()=>{setBusy(true);try{await removeEmployee(remove);setRemove(null);setNotice('Employee deleted. Existing attendance and salary slips kept.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Yes, delete {remove.name}</button><button disabled={busy} className="border p-3 rounded bg-white" onClick={()=>setRemove(null)}>← Back</button></div></div>}
 </section>;
}
