import {generateListingDraft,compressedListingPhoto} from '../../services/listingAIService';
import React,{useEffect,useRef,useState} from 'react';
import {factualListingDraft,imageDraftSize,type ListingFacts} from '../../lib/listingAssistant';
interface Props{name:string;listingType:'retail'|'b2b';originals:string[];disabled:boolean;onDescription:(v:string)=>void;onPhoto:(v:string)=>void;}
export function ListingAssistant({name,listingType,originals,disabled,onDescription,onPhoto}:Props){
 const generation=useRef(0);const [facts,setFacts]=useState({material:'',dimensions:'',included:'',use:'',care:''}),[copy,setCopy]=useState(''),[claims,setClaims]=useState<string[]>([]),[ai,setAI]=useState(false),[after,setAfter]=useState(''),[info,setInfo]=useState(''),[error,setError]=useState(''),[working,setWorking]=useState(false),[brightness,setBrightness]=useState(100),[target,setTarget]=useState<800|2048|4096>(2048),[index,setIndex]=useState(0);
 useEffect(()=>{generation.current++;setCopy('');setClaims([]);setAI(false);setInfo('');},[name,listingType,facts]);
 useEffect(()=>{generation.current++;setAfter('');setInfo('');},[originals,brightness,target,index]);useEffect(()=>()=>{generation.current++;},[]);
 async function aiDraft(){const version=generation.current;setWorking(true);setError('');try{const photo=originals[index]?await compressedListingPhoto(originals[index]):undefined;const result=await generateListingDraft({name,listingType,...facts},photo);if(version!==generation.current)return;setCopy(result.description);setClaims(result.claimsToCheck);setAI(true);setInfo('AI draft ready. Check every claim before using it. Nothing is published.');}catch(e:any){setError(e.message);}finally{setWorking(false);}}
 function draft(){setAI(false);setClaims([]);try{setCopy(factualListingDraft({name,listingType,...facts} as ListingFacts));setError('');}catch(e:any){setError(e.message);}}
 async function photo(){const version=generation.current;setWorking(true);setError('');try{if(!originals[index])throw Error('Choose a real product photo first.');const bitmap=await createImageBitmap(await(await fetch(originals[index])).blob());try{const size=imageDraftSize(bitmap.width,bitmap.height,target),canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const c=canvas.getContext('2d');if(!c)throw Error('Image editor unavailable.');c.fillStyle='white';c.fillRect(0,0,size.width,size.height);c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.filter=`brightness(${brightness}%)`;c.drawImage(bitmap,0,0,size.width,size.height);if(version!==generation.current)return;setAfter(canvas.toDataURL('image/jpeg',.9));setInfo(`${bitmap.width}×${bitmap.height} original → ${size.width}×${size.height} draft. ${size.enlarged?'Enlarged pixels, not AI-restored detail.':'Resized without inventing detail.'}`);}finally{bitmap.close();}}catch(e:any){setError(e.message);}finally{setWorking(false);}}
 async function usePhoto(){if(!after)return;const version=generation.current;setWorking(true);try{const bitmap=await createImageBitmap(await(await fetch(after)).blob());try{const size=imageDraftSize(bitmap.width,bitmap.height,800),canvas=document.createElement('canvas');canvas.width=size.width;canvas.height=size.height;const c=canvas.getContext('2d')!;c.drawImage(bitmap,0,0,size.width,size.height);let result='';for(const q of [.8,.65,.5,.35]){result=canvas.toDataURL('image/jpeg',q);if(result.length<=110000)break;}if(result.length>110000)throw Error('Draft is too detailed for current listing storage. Original has not changed.');if(version!==generation.current)return;onPhoto(result);setInfo(v=>v+' Cover copied at max800px for existing listing storage. HD original is not saved to the catalog.');}finally{bitmap.close();}}catch(e:any){setError(e.message);}finally{setWorking(false);}}
 const lock=disabled||working,control='w-full border border-slate-300 rounded-lg p-3 bg-white';
 return <section className="border border-slate-200 rounded-xl p-4 space-y-4 bg-slate-50" aria-label="Listing assistant draft workspace"><h3 className="font-bold text-lg">Listing assistant: photo and description drafts</h3><p className="text-sm">Retail and wholesale. Free photo editing and factual copy are ready here. Owner-only Gemini description drafts use public product facts and the selected product photo only. Free-tier quota applies; no paid fallback. HD detail restoration and 3D rendering are not connected.</p><p className="text-xs bg-amber-50 border border-amber-200 rounded p-3">Original photos stay only in this session and are lost on reload. Current catalog stores compressed max800px photos, not HD/4K masters. Resize is not AI enhancement. Keep real colour, logo, parts and proportions.</p>
 <fieldset disabled={lock} className="space-y-3"><legend className="font-semibold mb-2">Verified product facts</legend><div className="grid sm:grid-cols-2 gap-3">{Object.entries({material:'Material',dimensions:'Dimensions / capacity',included:'Included parts',use:'Intended use',care:'Care instructions'}).map(([k,label])=><label key={k} className="text-sm">{label}<input className={control} maxLength={500} value={facts[k as keyof typeof facts]} placeholder="Only if verified" onChange={e=>setFacts(v=>({...v,[k]:e.target.value}))}/></label>)}</div><button type="button" onClick={aiDraft} className="border rounded-lg p-3 bg-white">Generate AI description draft</button><p className="text-xs">Do not enter customer, HR or private details. Only public product facts/photo go to Google. Google free-tier data terms apply.</p><button type="button" onClick={draft} className="border rounded-lg p-3 bg-white">Prepare factual description draft</button></fieldset>
 {claims.length>0&&<div className="text-sm bg-amber-50 p-3 rounded"><p>Claims to check:</p><ul>{claims.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}{copy&&<div className="space-y-2"><label className="text-sm font-semibold">Review description<textarea className={control} value={copy} maxLength={4000} disabled={lock} onChange={e=>setCopy(e.target.value)} rows={6}/></label><button type="button" disabled={lock} onClick={()=>{onDescription(copy);setInfo('Description copied into the form. Review product before publishing.');}} className="border rounded-lg p-3 bg-white">Use reviewed description</button><p className="text-xs">{ai?'AI draft: review facts and photo-only claims.':'Fact-based template, not generative AI.'} Price, stock, tax and shipping stay unchanged.</p></div>}
 <fieldset disabled={lock} className="space-y-3"><legend className="font-semibold mb-2">Photo draft</legend><div className="grid sm:grid-cols-3 gap-3"><label className="text-sm">Real photo<select className={control} value={index} onChange={e=>setIndex(Number(e.target.value))}>{originals.map((_,i)=><option key={i} value={i}>Photo {i+1}</option>)}</select></label><label className="text-sm">Longest edge<select className={control} value={target} onChange={e=>setTarget(Number(e.target.value) as 800|2048|4096)}><option value={800}>800px catalog</option><option value={2048}>2048px draft</option><option value={4096}>4096px draft</option></select></label><label className="text-sm">Lighting: {brightness}%<input className="w-full mt-3" type="range" min={90} max={110} value={brightness} onChange={e=>setBrightness(Number(e.target.value))}/></label></div><button type="button" disabled={lock||!originals.length} onClick={photo} className="border rounded-lg p-3 bg-white">{working?'Preparing...':'Preview photo draft'}</button></fieldset>
 {(originals[index]||after)&&<div className="grid sm:grid-cols-2 gap-3">{originals[index]&&<figure><img src={originals[index]} alt="Original product photo" className="w-full h-48 object-contain bg-white rounded border"/><figcaption className="text-xs mt-1">Original, unchanged</figcaption></figure>}{after&&<figure><img src={after} alt="Edited product photo draft" className="w-full h-48 object-contain bg-white rounded border"/><figcaption className="text-xs mt-1">Local edit draft, not AI-generated</figcaption></figure>}</div>}
 {after&&<button type="button" disabled={lock} onClick={usePhoto} className="border rounded-lg p-3 bg-white">Use reviewed draft as catalog cover</button>}{info&&<p role="status" className="text-sm break-words">{info}</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<p className="text-xs">Nothing goes live here. Owner product review and Publish still required.</p></section>;
}
