import{decimal,realDate,rupees}from'../gst-computation-stage/model';
export type StockFact={id:string;sku:string;name:string;stock:number|null;warehouse:boolean;source:string;checkedAt:string};
export function reorderSuggestions(facts:StockFact[],threshold:number,target:number){if(!Number.isSafeInteger(threshold)||threshold<0||!Number.isSafeInteger(target)||target<threshold)throw Error('Review integer threshold and target.');return facts.map(f=>({...f,status:!f.warehouse?'supplier-availability-not-warehouse':!Number.isSafeInteger(f.stock)||f.stock!<0?'stock-unverified':f.stock!<=threshold?'review-reorder':'above-threshold',suggested:f.warehouse&&Number.isSafeInteger(f.stock)&&f.stock!>=0&&f.stock!<=threshold?Math.max(0,target-f.stock!):null}));}
export type PackingLine={sku:string;quantity:number};
export function packingScan(expected:PackingLine[],scans:string[]){if(!expected.length||expected.some(l=>!l.sku||!Number.isSafeInteger(l.quantity)||l.quantity<1)||new Set(expected.map(l=>l.sku)).size!==expected.length)throw Error('Review uniquely identified expected SKUs/quantities.');const count=new Map<string,number>();for(const sku of scans){const line=expected.find(l=>l.sku===sku);if(!line)throw Error('Unexpected barcode/SKU: '+sku);const n=(count.get(sku)||0)+1;if(n>line.quantity)throw Error('Too many scans for '+sku);count.set(sku,n);}return expected.map(l=>({...l,scanned:count.get(l.sku)||0,remaining:l.quantity-(count.get(l.sku)||0)}));}
export type WorkflowDraft={kind:'hr-correction'|'leave'|'salary';employeeId:string;period:string;startDate:string;endDate:string;basic:string;allowances:string;deductions:string;reason:string;source:string;currentValue?:string;proposedValue?:string;leaveType?:string};
export function validateWorkflow(d:WorkflowDraft){if(!['hr-correction','leave','salary'].includes(d.kind)||!d.employeeId.trim()||d.employeeId.length>128||!d.reason.trim()||d.reason.length>1000||!d.source.trim()||d.source.length>1000)throw Error('Employee identity, reason and reviewed source required.');if(d.kind==='salary'){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(d.period))throw Error('Review salary month.');const base=decimal(d.basic),allow=decimal(d.allowances),deduct=decimal(d.deductions);if(deduct>base+allow)throw Error('Deductions exceed salary gross.');return{...d,net:rupees(base+allow-deduct)};}if(d.kind==='hr-correction'&&(!d.currentValue?.trim()||!d.proposedValue?.trim()||d.currentValue===d.proposedValue))throw Error('Record current and proposed correction values; identical is no correction.');if(d.kind==='leave'&&!['paid-request','unpaid-request','sick-request','other-request'].includes(d.leaveType||''))throw Error('Review leave request type. Approval remains pending.');if(!realDate(d.startDate)||!realDate(d.endDate)||d.startDate>d.endDate)throw Error('Review correction/leave date range.');return{...d,net:null};}
export function dueReminders(rows:{id:string;dueDate:string;status:string;note:string}[],today:string){if(!realDate(today))throw Error('Review local date anchor.');return rows.filter(r=>realDate(r.dueDate)&&r.dueDate<=today&&!['won','closed'].includes(r.status)).map(r=>({...r,state:r.dueDate<today?'overdue-review':'due-today-review'}));}
export function ownerSummary(input:{ordersLoaded:boolean;orders:number;referencesLoaded:boolean;unreconciled:number;stockLoaded:boolean;lowStock:number;crmLoaded:boolean;due:number;healthCheckedAt:string;costKnown:boolean}){return[{label:'Own-store orders',value:input.ordersLoaded?String(input.orders)+' loaded server records':'unverified'},{label:'Unreconciled sources',value:input.referencesLoaded?String(input.unreconciled)+' loaded-view sources':'unverified'},{label:'Low warehouse stock',value:input.stockLoaded?String(input.lowStock)+' review suggestions':'unverified'},{label:'CRM due reviews',value:input.crmLoaded?String(input.due)+' due/overdue':'unverified'},{label:'Health',value:input.healthCheckedAt?'Checked '+input.healthCheckedAt:'not checked'},{label:'Cost / budget',value:input.costKnown?'source-backed review available':'current billing/usage not verified'}];}

export function workflowConflicts(rows:(WorkflowDraft&{id:string})[]){const keys=new Map<string,number>();const key=(r:WorkflowDraft)=>[r.kind,r.employeeId,r.kind==='salary'?r.period:r.startDate+'|'+r.endDate].join('|');rows.forEach(r=>keys.set(key(r),(keys.get(key(r))||0)+1));return rows.map(r=>({...r,conflict:(keys.get(key(r))||0)>1}));}
