import {prepareIndexMutation} from '../../public/catalog-index-core.mjs';
import {collection,doc,getDocFromServer,onSnapshot,runTransaction} from 'firebase/firestore';
import {auth,db} from './config';
import {ADMIN_EMAILS} from './firestoreService';
import {sameListing} from '../lib/productListing';
import type {Product} from '../types';
export function requireListingOwner(){const u=auth.currentUser;if(!u||!u.emailVerified||!ADMIN_EMAILS.includes((u.email||'').toLowerCase()))throw Error('Sign in with your authorized owner Google account first.');return u.uid;}
export function subscribeServerListings(onData:(products:Product[])=>void,onError:(error:Error)=>void){return onSnapshot(collection(db,'products'),{includeMetadataChanges:true},snap=>{if(snap.metadata.fromCache||snap.metadata.hasPendingWrites)return;onData(snap.docs.map(d=>({...d.data(),id:d.id} as Product)));},onError);}
export async function createOwnerListing(product:Product){requireListingOwner();const ref=doc(db,'products',product.id);const fields={...product,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await runTransaction(db,async tx=>{requireListingOwner();const before=await tx.get(ref);if(before.exists()){const {createdAt,updatedAt,...saved}=before.data();if(sameListing(saved,product as any))return;throw Error('This listing reference already exists. Nothing overwritten.');}const indexWrite=await prepareIndexMutation(tx,db,doc,product.id,null,fields);tx.set(ref,fields);indexWrite();});const after=await getDocFromServer(ref);if(!after.exists())throw Error('Save could not be verified. Keep this form and check the live list before trying again.');const {createdAt,updatedAt,...saved}=after.data();if(!sameListing(saved,product as any))throw Error('Saved listing differs. Check the live list before trying again.');}
export async function deleteOwnerListing(product:Product){requireListingOwner();const ref=doc(db,'products',product.id);const fresh=await getDocFromServer(ref);if(!fresh.exists())return;const expected={...fresh.data(),id:fresh.id};if(!sameListing(expected,product as any))throw Error('Product changed since you opened Delete. Refresh the list and review it again.');await runTransaction(db,async tx=>{requireListingOwner();const current=await tx.get(ref);if(!current.exists())return;if(!sameListing({...current.data(),id:current.id},expected))throw Error('Product changed. Nothing deleted. Review again.');const indexWrite=await prepareIndexMutation(tx,db,doc,product.id,current.data(),null);tx.delete(ref);indexWrite();});if((await getDocFromServer(ref)).exists())throw Error('Deletion could not be verified. Check the live list before trying again.');}

// Metadata edits never replace stock/reservations, SKU, supplier or original order fields.
export async function editOwnerListing(opened:Product,input:import('../lib/productEdit').ProductEditInput){const uid=requireListingOwner(),{productEditPatch}=await import('../lib/productEdit'),patch=productEditPatch(opened,input),ref=doc(db,'products',opened.id),audit=doc(collection(db,'productChangeAudit')),now=new Date().toISOString();await runTransaction(db,async tx=>{if(requireListingOwner()!==uid)throw Error('Owner changed.');const fresh=await tx.get(ref);if(!fresh.exists()||!sameListing({...fresh.data(),id:fresh.id},opened as any))throw Error('Product changed, including stock reservation. Refresh and review again.');const before=fresh.data(),after={...before,...patch,updatedAt:now,productChangeAuditId:audit.id};const index=await prepareIndexMutation(tx,db,doc,opened.id,before,after);tx.update(ref,{...patch,updatedAt:now,productChangeAuditId:audit.id});tx.set(audit,{productId:opened.id,action:'metadata-edit',before,after,actorUid:uid,at:now});index();});const saved=await getDocFromServer(ref);if(requireListingOwner()!==uid||!saved.exists()||saved.data().productChangeAuditId!==audit.id)throw Error('Edit readback unverified. Refresh before retry.');}
export async function archiveOwnerListing(opened:Product,reason:string){const uid=requireListingOwner();if(!reason.trim()||reason.length>500)throw Error('Archive reason required, max500 characters.');const ref=doc(db,'products',opened.id),audit=doc(collection(db,'productChangeAudit')),now=new Date().toISOString();await runTransaction(db,async tx=>{if(requireListingOwner()!==uid)throw Error('Owner changed.');const fresh=await tx.get(ref);if(!fresh.exists()||!sameListing({...fresh.data(),id:fresh.id},opened as any))throw Error('Product changed. Refresh and review archive again.');const before=fresh.data();if(before.gatewayVerification||before.hidden||before.supplier==='rajkot'||before.stockManaged===false)throw Error('Supplier-linked, hidden or verification products cannot be archived here.');const patch={hidden:true,archiveReason:reason.trim(),archivedBy:uid,archivedAt:now,updatedAt:now,productChangeAuditId:audit.id},after={...before,...patch};const index=await prepareIndexMutation(tx,db,doc,opened.id,before,after);tx.update(ref,patch);tx.set(audit,{productId:opened.id,action:'archive',before,after,actorUid:uid,at:now});index();});const saved=await getDocFromServer(ref);if(requireListingOwner()!==uid||!saved.exists()||saved.data().hidden!==true||saved.data().productChangeAuditId!==audit.id)throw Error('Archive readback unverified. Refresh.');}
