import {collection,query,orderBy,limit,getDocsFromServer,doc,runTransaction,serverTimestamp,getDocFromServer} from 'firebase/firestore';
import {auth,db} from '../firebase/config';
export const owners=['sksaharukhossain1996@gmail.com','ecommerceunickdigital@gmail.com'];
export function owner(){const u=auth.currentUser;if(!u?.emailVerified||!owners.includes((u.email||'').toLowerCase()))throw Error('Verified owner sign-in required.');return u;}
export type Row={id:string;[k:string]:any};
export async function readRows(name:string,sort?:string,count=100){const u=owner();const q=query(collection(db,name),...(sort?[orderBy(sort,'desc')]:[]),limit(count));const s=await getDocsFromServer(q);if(owner().uid!==u.uid)throw Error('Account changed');return{rows:s.docs.map(d=>({id:d.id,...d.data()}as Row)),capped:s.size===count};}
export async function saveFollowUp(key:string,input:{source:string;sourceId:string;status:string;note:string;dueDate:string},expected:string|null){const u=owner();if(!['customers','orders','investorLeads','inquiries'].includes(input.source)||!['new','contacted','qualified','waiting','won','closed'].includes(input.status)||input.note.length>3000||!/^$|^\d{4}-\d{2}-\d{2}$/.test(input.dueDate))throw Error('Review follow-up fields');const ref=doc(db,'crmFollowUps',key);await runTransaction(db,async tx=>{if(owner().uid!==u.uid)throw Error('Account changed');const d=await tx.get(ref);const current=d.exists()?d.data().revision:null;if(current!==expected)throw Error('Follow-up changed. Refresh before saving.');tx.set(ref,{...input,updatedBy:u.uid,updatedAt:serverTimestamp(),revision:crypto.randomUUID()})});const d=await getDocFromServer(ref);if(owner().uid!==u.uid||!d.exists())throw Error('Save not confirmed');return{id:d.id,...d.data()}as Row;}
export function text(v:any){return typeof v==='string'?v:''}
export function rupees(v:any){return typeof v==='number'&&Number.isFinite(v)?new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v):'Not recorded'}
export function dateText(v:any){const d=v?.toDate?.()||new Date(v);return Number.isFinite(d?.getTime?.())?d.toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Not recorded'}
