import{saveExport}from'../lib/exportFile';
import type{GstDraft}from './draftInvoices';import type{CompanyInfo}from '../types';
const headers=['Invoice number','Invoice date','Customer','Recipient GSTIN','POS','Taxable INR','CGST INR','SGST INR','IGST INR','Invoice INR','Source order','Status'];
const values=(d:GstDraft)=>[d.invoiceNumber,d.invoiceDate,d.customerName,d.recipientGstin,d.placeOfSupply,d.taxableValue,d.cgst,d.sgst,d.igst,d.invoiceValue,d.sourceOrderId,d.status];
const logoUrl='/UDECS_Logo_Premium_Transparent.png';
async function logo(){const r=await fetch(logoUrl);if(!r.ok)throw Error('Original UDECS logo unavailable. Export stopped.');const b=await r.blob();return await new Promise<string>((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(String(f.result));f.onerror=reject;f.readAsDataURL(b)});}
export async function exportGstXlsx(rows:GstDraft[],company:CompanyInfo,period:string){
 const{default:ExcelJS}=await import('exceljs'),wb=new ExcelJS.Workbook(),ws=wb.addWorksheet('GST draft invoices');wb.creator=company.legalName;
 const image=wb.addImage({base64:await logo(),extension:'png'});ws.addImage(image,{tl:{col:0,row:0},ext:{width:85,height:65}});ws.mergeCells('B1:L1');ws.getCell('B1').value=company.legalName;ws.getCell('B1').font={bold:true,size:18};ws.mergeCells('B2:L2');ws.getCell('B2').value='UDECS | udecs.store';ws.mergeCells('B3:L3');ws.getCell('B3').value=`GSTIN: ${company.gstin} | ${company.address}`;
 ws.mergeCells('A5:L5');ws.getCell('A5').value=`DRAFT INVOICE REGISTER | ${period||'All periods'} | Not filed, not reconciled`;ws.getCell('A5').font={bold:true,color:{argb:'FF9C2D20'}};ws.addRow([]);ws.addRow(headers);
 rows.forEach(d=>ws.addRow(values(d)));const bottom=ws.rowCount+2;ws.mergeCells(`B${bottom}:L${bottom}`);ws.getCell(`B${bottom}`).value=`${company.legalName} | udecs.store | Internal draft records only`;ws.addImage(image,{tl:{col:0,row:bottom-1},ext:{width:60,height:45}});
 ws.columns.forEach((c,i)=>c.width=i===2?28:i===10?35:18);ws.getColumn(10).alignment={horizontal:'right'};ws.getColumn(11).alignment={horizontal:'left',indent:1};ws.eachRow((r,n)=>{r.height=n===1?30:24;r.eachCell(c=>{c.alignment={vertical:'middle',wrapText:true,horizontal:typeof c.value==='number'?'right':'left'};if(n===7){c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF182620'}};c.font={bold:true,color:{argb:'FFFFFFFF'}};}if(n>=8&&n<bottom-1)c.border={bottom:{style:'thin',color:{argb:'FFCBCFB9'}}};});});for(let r=8;r<8+rows.length;r++)for(let c=6;c<=10;c++)ws.getCell(r,c).numFmt='#,##0.00';ws.views=[{state:'frozen',ySplit:7}];ws.autoFilter={from:'A7',to:`L${7+rows.length}`};ws.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};
 const buf=await wb.xlsx.writeBuffer();await download(new Blob([buf as BlobPart],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),`UDECS-GST-Draft-${period||'all'}.xlsx`);
}
export async function exportGstPdf(rows:GstDraft[],company:CompanyInfo,period:string){
 const{jsPDF}=await import('jspdf'),pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),img=await logo();let y=44,page=1;
 const header=()=>{pdf.addImage(img,'PNG',10,7,20,20);pdf.setFontSize(14);pdf.text(company.legalName,34,13);pdf.setFontSize(9);pdf.text(`UDECS | udecs.store | GSTIN ${company.gstin}`,34,20);pdf.text('Draft invoice register - NOT FILED / NOT RECONCILED',10,34);pdf.text(`Period: ${period||'All'} | Internal draft records, not original orders`,10,39);pdf.setFillColor(24,38,32);pdf.rect(10,42,277,8,'F');pdf.setTextColor(255);pdf.setFontSize(7);['Invoice / Date','Customer / GSTIN / POS','Taxable','CGST','SGST','IGST','Invoice INR'].forEach((t,i)=>pdf.text(t,[12,65,163,192,215,239,263][i],47));pdf.setTextColor(0);y=52;};
 const footer=()=>{pdf.addImage(img,'PNG',10,190,12,12);pdf.setFontSize(8);pdf.text(`${company.legalName} | udecs.store | Draft only`,25,198);pdf.text(`Page ${page}`,273,198);};header();
 rows.forEach(d=>{const name=pdf.splitTextToSize(d.customerName,90);const height=Math.max(14,name.length*3.5+7);if(y+height>185){footer();pdf.addPage();page++;header();}pdf.setFontSize(7);pdf.text([d.invoiceNumber,d.invoiceDate],12,y+4);pdf.text([...name,`${d.recipientGstin||'B2C'} | POS ${d.placeOfSupply}`],65,y+4);[d.taxableValue,d.cgst,d.sgst,d.igst,d.invoiceValue].forEach((v,i)=>pdf.text(v.toFixed(2),[163,192,215,239,263][i],y+4));pdf.setDrawColor(203,207,185);pdf.line(10,y+height,287,y+height);y+=height;});if(!rows.length)pdf.text('No active drafts in this selected period.',12,58);footer();await saveExport(pdf.output("blob"),`UDECS-GST-Draft-${period||'all'}.pdf`);
}
const download=saveExport;
