import {useLocalBack} from '../navigation/ManagementBack';
import React,{useEffect,useState}from 'react';import type{CompanyInfo}from '../types';import{EMPTY_GST_DRAFT,GST_FIELDS,GstDraft,GstDraftInput}from './draftInvoices';import{readGstDrafts,newGstDraftId,saveGstDraft,archiveGstDraft}from './draftService';import{exportGstPdf,exportGstXlsx}from './draftExports';
const labels:Record<string,string>={invoiceNumber:'Invoice number (from invoice)',invoiceDate:'Invoice date',customerName:'Customer name',recipientGstin:'Recipient GSTIN (blank for B2C)',placeOfSupply:'POS state code (from invoice)',taxableValue:'Taxable value INR',cgst:'CGST INR',sgst:'SGST INR',igst:'IGST INR',invoiceValue:'Invoice value INR',sourceOrderId:'Source order reference (optional)',note:'Review note / source'};
export function GstDraftRegister({company}:{company:CompanyInfo}){
 const[rows,setRows]=useState<GstDraft[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[period,setPeriod]=useState(''),[archived,setArchived]=useState(false),[selected,setSelected]=useState<GstDraft|null>(null),[form,setForm]=useState<GstDraftInput|null>(null),[saveId,setSaveId]=useState('');
useLocalBack(!!form,'Back to GST list',()=>{if(busy)return;setForm(null)}); const refresh=async()=>{setLoaded(false);try{setRows(await readGstDrafts());setLoaded(true);}catch(e){setError(String(e));}};useEffect(()=>{void refresh()},[]);
 const visible=rows.filter(r=>(archived||r.status==='draft')&&(!period||r.invoiceDate.slice(0,7)===period));const exports=visible.filter(r=>r.status==='draft');
 const work=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}};
 const edit=()=>{if(!selected||selected.status!=='draft')return;setSaveId(selected.id);setForm(Object.fromEntries(GST_FIELDS.map(k=>[k,selected[k]]))as GstDraftInput)};
 return <section className="bg-white border border-[#CBCFB9] rounded-xl p-4 space-y-3"><h2 className="font-bold text-xl">GST invoice drafts</h2><p className="text-sm">Separate internal register. Add/Edit/Delete never change original orders, payments or filed returns. Delete archives the draft and keeps its audit history. Exports include active drafts only, not the order summary below.</p>
 <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>{setSelected(null);setSaveId(newGstDraftId());setForm({...EMPTY_GST_DRAFT})}} className="border rounded px-3 py-2">Add</button><button disabled={busy||!selected||selected.status!=='draft'}onClick={edit}className="border rounded px-3 py-2">Edit</button><button disabled={busy||!selected||selected.status!=='draft'}onClick={()=>{if(!selected)return;const reason=window.prompt('Delete archives this draft permanently from active reports. Original record and audit retained. Enter reason:');if(reason)void work(async()=>{await archiveGstDraft(selected,reason);setSelected(null);await refresh();})}}className="border rounded px-3 py-2">Delete (archive)</button><button disabled={busy||!loaded}onClick={()=>void work(()=>exportGstPdf(exports,company,period))}className="border rounded px-3 py-2">Export to PDF</button><button disabled={busy||!loaded}onClick={()=>void work(()=>exportGstXlsx(exports,company,period))}className="border rounded px-3 py-2">Export to XLS (XLSX)</button><button disabled={busy}onClick={()=>void refresh()}className="border rounded px-3 py-2">Refresh</button></div>
 <div className="flex flex-wrap items-center gap-3 text-sm"><label>Invoice month <input type="month"value={period}onChange={e=>{setPeriod(e.target.value);setSelected(null)}}className="border p-2 rounded"/></label><label><input type="checkbox"checked={archived}onChange={e=>setArchived(e.target.checked)}/> Show archived</label><span>{loaded?`${visible.length} drafts displayed (${exports.length} active for export)`:'Loading verified drafts...'}</span></div>{error&&<p role="alert"className="text-red-700">{error}</p>}
 <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Select','Invoice / Date','Customer / GSTIN','POS','Taxable','CGST','SGST','IGST','Invoice INR','Status'].map(h=><th key={h}className="text-left p-2 bg-[#EEF0E7]">{h}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}className={selected?.id===r.id?'bg-[#EEF0E7]':''}><td className="p-2"><input type="radio"name="gstDraft"aria-label={`Select ${r.invoiceNumber}`}checked={selected?.id===r.id}onChange={()=>setSelected(r)}/></td><td className="p-2">{r.invoiceNumber}<br/>{r.invoiceDate}</td><td className="p-2">{r.customerName}<br/>{r.recipientGstin||'B2C'}</td><td>{r.placeOfSupply}</td>{[r.taxableValue,r.cgst,r.sgst,r.igst,r.invoiceValue].map((v,i)=><td key={i}className="p-2">{Number(v).toFixed(2)}</td>)}<td>{r.status} (v{r.revision})</td></tr>)}</tbody></table>{loaded&&!visible.length&&<p className="p-4">No invoice drafts in this view. Nothing has been imported or filed.</p>}</div>
 {form&&<div role="dialog"aria-label="GST draft editor"className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form className="bg-white rounded-xl p-5 max-w-3xl w-full max-h-[90vh]overflow-auto space-y-3"onSubmit={e=>{e.preventDefault();void work(async()=>{await saveGstDraft(saveId,form,selected||undefined);setForm(null);setSelected(null);await refresh();})}}><h3 className="text-xl font-bold">{selected?'Edit':'Add'} internal GST draft</h3><p>Enter values from a reviewed invoice. No tax rate or POS is guessed. This is not a government filing.</p><div className="grid sm:grid-cols-2 gap-3">{GST_FIELDS.map(k=><label key={k}className="text-sm">{labels[k]}<input className="block w-full border rounded p-2"type={typeof form[k]==='number'?'number':k==='invoiceDate'?'date':'text'}step={typeof form[k]==='number'?'0.01':undefined}min={typeof form[k]==='number'?0:undefined}value={form[k]}onChange={e=>setForm({...form,[k]:typeof form[k]==='number'?Number(e.target.value):e.target.value})}/></label>)}</div>{error&&<p role="alert"className="text-red-700">{error}</p>}<button disabled={busy}className="border rounded px-4 py-2 bg-[#182620] text-white">{busy?'Saving...':'Save draft'}</button><button type="button"disabled={busy}onClick={()=>setForm(null)}className="border rounded px-4 py-2 ml-2">← Back</button></form></div>}
 </section>;
}
