import{collection,doc,getDocsFromServer,getDocFromServer,limit,orderBy,query,runTransaction}from 'firebase/firestore';import{auth,db}from '../firebase/config';import{planStockChange,sameStockRequest,StockChangeInput}from './stockAdjustment';
export type StockAdjustment=StockChangeInput&{id:string;sku:string;beforeStock:number;afterStock:number;createdBy:string;createdAt:string;status:'active'|'archived';revision:number;note:string;updatedBy:string;updatedAt:string;auditId:string};
function owner(){const u=auth.currentUser;if(!u?.emailVerified||!['sksaharukhossain1996@gmail.com','ecommerceunickdigital@gmail.com'].includes(u.email?.toLowerCase()||''))throw Error('Verified owner sign-in required.');return u.uid;}
export function newStockAdjustmentId(){return doc(collection(db,'stockAdjustments')).id;}
export async function readStockAdjustments(){const uid=owner();const s=await getDocsFromServer(query(collection(db,'stockAdjustments'),orderBy('createdAt','desc'),limit(101)));if(owner()!==uid)throw Error('Account changed.');if(s.size>100)throw Error('More than 100 adjustments: filtered paging is required. No partial export.');return s.docs.map(d=>({...d.data(),id:d.id}as StockAdjustment));}
export async function applyStockAdjustment(id:string,input:StockChangeInput){const uid=owner(),now=new Date().toISOString(),audit=doc(collection(db,'stockAdjustmentAudit'));
 await runTransaction(db,async tx=>{if(owner()!==uid)throw Error('Account changed.');const entry=doc(db,'stockAdjustments',id),product=doc(db,'products',input.productId),old=await tx.get(entry);if(old.exists()){const d=old.data()as StockAdjustment;if(d.createdBy===uid&&sameStockRequest(d,input))return;throw Error('Adjustment ID already exists. Refresh before retry.');}const p=await tx.get(product);if(!p.exists())throw Error('Product missing. Refresh.');const plan=planStockChange({...p.data(),id:p.id}as any,input);const after={...plan.input,sku:plan.sku,beforeStock:plan.beforeStock,afterStock:plan.afterStock,createdBy:uid,createdAt:now,status:'active',revision:1,note:'',updatedBy:uid,updatedAt:now,auditId:audit.id};tx.update(product,{stock:plan.afterStock,updatedAt:now,stockAdjustmentId:id});tx.set(entry,after);tx.set(audit,{adjustmentId:id,action:'add',before:null,after,actorUid:uid,at:now});});
 const stored=await getDocFromServer(doc(db,'stockAdjustments',id));if(owner()!==uid||!stored.exists()||stored.data().createdBy!==uid||!sameStockRequest(stored.data() as StockChangeInput,input))throw Error('Save readback unverified. Keep this adjustment ID and refresh before any retry.');
}
export async function reviseStockAdjustment(opened:StockAdjustment,note:string,archiveReason?:string){const uid=owner(),now=new Date().toISOString();if(note.length>1000)throw Error('Note is too long.');if(archiveReason!==undefined&&(!archiveReason.trim()||archiveReason.length>500))throw Error('Archive reason required (max 500 characters).');const audit=doc(collection(db,'stockAdjustmentAudit'));
 await runTransaction(db,async tx=>{if(owner()!==uid)throw Error('Account changed.');const ref=doc(db,'stockAdjustments',opened.id),old=await tx.get(ref);if(!old.exists()||old.data().revision!==opened.revision||old.data().status!=='active')throw Error('Adjustment changed or archived. Refresh.');const before=old.data(),after={...before,note:note.trim(),status:archiveReason?'archived':'active',...(archiveReason?{archiveReason:archiveReason.trim()}:{}),revision:opened.revision+1,updatedBy:uid,updatedAt:now,auditId:audit.id};tx.update(ref,after);tx.set(audit,{adjustmentId:opened.id,action:archiveReason?'archive':'edit-note',before,after,actorUid:uid,at:now});});
 const stored=await getDocFromServer(doc(db,'stockAdjustments',opened.id));if(owner()!==uid||!stored.exists()||stored.data().revision!==opened.revision+1||stored.data().auditId!==audit.id)throw Error('Change readback unverified. Refresh before any retry.');
                                                                                                     }
